Standardize cutscene and victory UX
wesnoth/wesnoth pull request #5534
Opened 2021-02-12 16:51 UTC by hexagonrecursion

Fixes #5514

Your user experience gives me as a player certain expectations:
* When a cutscene ends the game automatically moves on to the next scenario without a victory popup or linger mode
* When a regular scenario ends:
  * The music changes to victory.ogg or victory2.ogg
  * A victory popup is shown
  * The game enters the linger mode

Scenarios that violate this expectations surprise and confuse me. This PR fixes every such scenario that I was able to find in the mainline campaigns.

2021-02-12 17:54 UTC, knyghtmare reviewed
My review is mostly constructive and I have added reasoning for any changes.

- Dead Water S13 (Epilogue): This is fine as I recall this is the last scenario.
- DM (S22): I don't think a carryover report should be shown in this scenario as it is clearly the last scenario of the campaign
- DiD (S7abc): These scenarios are meant to be a single continuation of Malin and Volk's mission to "retrieve" the book. I don't think carryover reports should be displayed at all here as there is no recruiting after Scenario 7A, and the gold is fully carried over.
- S10 (Endless Night): I see changes have been made to the "secret" endings. I don't see any point in displaying the carryover report here as this is the end of the campaign (and S10's loop) since it's not relevant to the player what gold would be carried over since `next_scenario=null`. I suppose linger can be shown.
- EI (final_battle utils): Same argument given in my previous case for S10 of DiD. I do agree with it having linger mode though.
- HttT (S24): Since the campaign ends with the Battle for Wesnoth, is there any point in showing how much gold the player gets carried over to an epilogue? I do not think so.
- LoW (S23): Same argument given for my previous 3 cases.
- Liberty (S7): Same argument made in my previous 4 cases. 
- NR (S13a), SoF S07, SoF S09, SotA S21, SotBE S18, THoT S09, TRoW S22, TSG S08a, TSG S08b, AToTB S04, UtBS S12: I listed all of these together as they all seem to be the same aforementioned argument.
- UtBS S07a and S07b: This was rather just a "recall someone to pick the sword" scenario and a cutscene so disabling linger mode here is perfectly fine.
- Battle Training (tutorial) S1: The `carryover_percentage=0` sort of nullifies any benefit from seeing a carryover report. Although a counter argument can be offered to allow new players to experience what a carryover report and point out some things in it, like how the values are calculated and when to consider getting the early finish bonus (over more XP for units) and retaining gold.

I have offered my feedback on these changes based on being a part of this community since 2010 and as an UMC author.

2021-02-13 00:03 UTC, Vultraz commented
I very much disagree that there always need be a carryover report shown. Some scenarios - especially the DiD ones, for instance - are explicitly designed to, as knyghtmare said, flow into one another smoothly and feel like one scenario. The use (or lack thereof) of carryover reports is almost always a creative decision and not an oversight, and so I would oppose merging this pr as-in.

2021-02-13 05:27 UTC, hexagonrecursion commented
The developer's / content creator's perspective: we wanted to make the gold carryover mechanic more obvious to the player. We added a popup to notify the player about it. There is no carryover in the last scenario of a campaign therefore there is no point in showing the popup.

Th player's perspective: when I win a scenario the music changes I see a popup telling me that I won. I expect this to happen every time I win a scenario.

2021-02-13 06:33 UTC, Pentarctagon commented
Repeating your opinion again will not by itself make it more convincing.

2021-02-13 06:39 UTC, hexagonrecursion commented
I did add something new this time. I have said: you are thinking like developers. Put yourself in the player's shoes.

2021-02-13 06:55 UTC, Vultraz commented
Except we are. We're considering the player experience, not favoring consistency for consistency's sake.

2021-02-13 21:32 UTC, CelticMinstrel commented
> The developer's / content creator's perspective: we wanted to make the gold carryover mechanic more obvious to the player. We added a popup to notify the player about it. There is no carryover in the last scenario of a campaign therefore there is no point in showing the popup.

But I think it does makes sense not to show information that is irrelevant. If there's no gold carryover, then why would you show the gold carryover information?

> Th player's perspective: when I win a scenario the music changes I see a popup telling me that I won. I expect this to happen every time I win a scenario.

On the other hand, this also makes a lot of sense. The popup _is_ a pretty good indication that you won.

But maybe there is a compromise solution. Logically, that WML key specifies whether to show the carryover report, _not_ whether to show the popup. Why not just show the popup _without_ including the gold carryover report in it? I don't know if there's anything else shown in the popup besides gold carryover, but you could easily add a generic "Victory!" message or something.

2021-02-14 09:18 UTC, nemaara requested changes

2021-02-14 09:18 UTC, nemaara commented on data/campaigns/Descent_Into_Darkness/scenarios/07a_A_Small_Favor.cfg
> -            linger_mode=no
Leave the DiD ones as they were originally please, including the ones for Endless Night.

2021-02-14 09:18 UTC, nemaara commented on data/campaigns/Under_the_Burning_Suns/scenarios/12_The_Final_Confrontation.cfg
> -            carryover_report=no
Leave this one as the original as well please.

2021-02-19 12:55 UTC, hexagonrecursion commented
@Wedge009

What caused me to open this issue is a specific subjective experience: when I won TSG and what I expected to happen did not happen I was confused. I asked myself: "Is this it or is there going to be more? Did the game break?" I attribute this confusion to me being a new player.

> But maybe there is a compromise solution. Logically, that WML key specifies whether to show the carryover report, _not_ whether to show the popup. Why not just show the popup _without_ including the gold carryover report in it?

This is indeed a better solution. I have somehow missed the fact that carryover information is currently always included in the popup. This sounds like something that would have to be implemented in C++ rather than wml

2021-02-19 13:12 UTC, Wedge009 commented
Thinking about the discussion from #5514, I remember that some decisions regarding scenario transitions are for story reasons, as others have already mentioned here. And unlike some, I see things more as a player than a developer so I understand what you're saying, but I don't necessarily agree with need for a pop-up. The grey tint of 'linger mode' and/or the victory music would be sufficient cues for me, but if you really feel the need for a pop-up of some sort, I'd agree with celmin's suggestion.

2021-03-07 19:07 UTC, Pentarctagon commented
At a minimum though, are the requested changes going to be made to this PR?

2021-05-03 19:39 UTC, Pentarctagon commented
Closing due to lack of response to nemaara's feedback.

2021-05-03 19:39 UTC, closed without merging