Improve the Load dialog's UX when there are no save files or corrupted files
wesnoth/wesnoth pull request #5563
Opened 2021-02-19 22:09 UTC by stevecotton

Re-add the popup that appears when "Load" is pressed on the title screen if
there are no files, but now check for files from previous versions too.

Improve handling of switching from a version with files to a version without
files, disabling buttons on the load dialog when there are no files in the
current directory.

This adds a \todo about the error path at the start of evaluate_summary_string,
this path is reached by creating empty files in the save dir. The dialog's state
is reasonable, so it seemed a low priority and I don't want to introduce new
bugs by refactoring this path now.

Fixes #5517

2021-02-20 08:23 UTC, stevecotton commented
I haven't added anything to the changelog for this, I think it's just a small change.

2021-02-22 03:13 UTC, Pentarctagon requested changes
Two issues that I noticed after testing locally:
* When deleting the last file for the current version, the Load Game dialog closes automatically.  I think it should stay open instead since the player might want to go look at another version's save files - I'd guess that the previous assumption when this dialog was designed was that once there are no save files left to display there's no longer any reason to show the dialog, but that assumption no longer necessarily holds true.
* When switching from the current version's saves to another version's saves the Delete button becomes disabled, but it should be allowed to delete another version's saves from the current version.  This happens regardless of whether or not the current version has any save files present.

2021-02-22 14:39 UTC, stevecotton commented
> When deleting the last file for the current version, it should stay open

Done.

> When switching to another version's saves the Delete button becomes disabled

I feel this should be done in a separate PR, as the logic of whether to deactivate the button is in `save_index_class::read_only()` and there's a corresponding guard in `save_index_class::delete_game()`. If I recall correctly from writing b66bdb8a1, that was added thinking about whether to create new saved games a directory where the current version of Wesnoth shouldn't update the save index, rather than thinking about deleting files.

However, once we start deleting files in the other versions' directories there will be futher questions of what should be done when the last file in the directory is deleted:
* should the directory itself be deleted?
* does there need to be more logic in `filesystem::find_other_version_saves_dirs()` to ignore empty directories?

2021-02-22 20:12 UTC, Pentarctagon commented
I'm fine with another PR.  For the two questions, I would say that the answer to both is no - for the first because if the player ever goes looking for the saves directory they then wouldn't be able to find it anymore, and for the second because I'd guess we'd get people asking why a particular version's directory isn't listed if we decide to hide it.

2021-02-22 20:14 UTC, Pentarctagon requested changes
The popup doesn't seem to be appearing when I have no save files at all.  Tested with empty save directories present for both 1.15 and 1.14.

2021-02-24 09:35 UTC, stevecotton commented
Fixed, it will now ignore empty directories when deciding whether to show the pop-up.

2021-02-24 19:46 UTC, Pentarctagon approved these changes

2021-02-24 20:18 UTC, merged