NR S1 Vary the die dialog depending on race
wesnoth/wesnoth pull request #6737
Opened 2022-05-31 15:47 UTC by Descacharrado

Closes #6735

The new strings are not set in stone.

2022-05-31 17:33 UTC, nemaara requested changes

2022-05-31 17:33 UTC, nemaara commented on data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
> +                            message= _ "We avenged our chief..."
Garrugch is not a chief, though. So you should probably switch this to leader or something

2022-05-31 17:33 UTC, nemaara commented on data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
> +                    message= _ "What the...? (<i>Gurgle</i>) Defeated... by... a lesser orc?"
Should use a less clunky term for lesser orc, say just a "grunt" or "whelp" or something of the like.

2022-06-01 00:03 UTC, merged

2022-06-01 00:03 UTC, Wedge009 commented
Ah, shoot, forgot to squash. Not a big deal, I hope.