Chore/map diff improvements
wesnoth/wesnoth pull request #6880
Opened 2022-07-17 03:35 UTC by macabeus

2022-07-19 19:19 UTC, soliton- requested changes

2022-07-19 19:19 UTC, soliton- commented on .github/workflows/map-diff.yml
> +          image_link=$($curl_result | jq -r ".data.link")
You probably meant:
```suggestion
          image_link=$(jq -r ".data.link" <<< "$curl_result")
```

2022-07-19 19:19 UTC, soliton- commented on .github/workflows/map-diff.yml
> +          curl_result=$(curl -X POST "https://api.imgur.com/3/upload" -F "image=@\"$diff_image\"")
Btw, -F implies POST adding -X is not useful. I would also put all options before positional parameters.

2022-07-19 19:19 UTC, soliton- commented on utils/wesnoth-map-diff/src/paint.ts
> +    output.composite(tileImage, x + leftPadding, y)
There really should be a check here or in `getTile` and error output if the tile isn't actually found.

2022-07-19 19:23 UTC, soliton- commented
I wonder if the change notes should rather be in the comment text not the image.

2022-07-19 19:29 UTC, soliton- commented
Ah, also something I wanted to mention... it'd be good to add some comments to the WML parser that it is by no means complete or accurate and just needs to parse terrain.cfg successfully. To make it clear that it's not useful for general use currently.

2022-07-20 08:14 UTC, macabeus commented on utils/wesnoth-map-diff/src/paint.ts
> +    const font = await Jimp.loadFont(fontPath)
Unfortunately, Jimp only supports `fnt`: https://github.com/oliver-moran/jimp/tree/master/packages/jimp#writing-text

2022-07-24 15:53 UTC, cooljeanius commented
Any plans to have it handle merge conflicts, too?

2022-07-25 07:59 UTC, macabeus commented
@cooljeanius Probably today at night, I'll can to do the requested changes

2022-07-31 19:49 UTC, macabeus commented
@soliton- 
> I wonder if the change notes should rather be in the comment text not the image.

I guess that it's better on the image, since probably always is necessary to open the image on a new tab. It'll be easier to read and spot the changes if the text is within the image.

2022-07-31 20:29 UTC, macabeus commented
@cooljeanius I don't have plans to add support to merge conflicts =/

2022-08-09 12:54 UTC, merged