Match lightning attacks to arcane damage icon
wesnoth/wesnoth pull request #6993
Opened 2022-09-01 17:06 UTC by Jonathan-Kelly

[A lightning bolt](https://github.com/wesnoth/wesnoth/blob/master/images/icons/profiles/arcane.png) is prominently displayed throughout the UI as the icon for arcane attacks. So switch the rare instances of lightning attacks from fire to arcane to match this convention. Doing so also makes the core Jinn unit more versatile, by giving it better utility against drakes (which are resistant to all its existing attack types).

2022-09-01 17:53 UTC, Pentarctagon commented
@nemaara just to check - does this have any meaningful impact on the balance of these campaigns?

2022-09-01 18:01 UTC, nemaara approved these changes

2022-09-01 18:01 UTC, nemaara commented
Well it does generally make them weaker but at least it helps differentiate lightning from fireball.

2022-09-01 18:13 UTC, CelticMinstrel commented
I don't really like this idea. Lightning doing fire damage totally makes sense, but arcane damage is an abstract sort of "magic" thing, so it doesn't fit lightning at all in my opinion.

2022-09-01 19:22 UTC, irydacea commented
Wouldn't it make more sense to change the icon? It could be something like sparks or stars instead.

2022-09-01 20:41 UTC, stevecotton commented
To me, that icon looks like a spiral seen side-on rather than a lightning bolt.

2022-09-01 23:30 UTC, knyghtmare requested changes
I do not agree with this. Lightning on hit... _Burns_...which is a fire attack by wesnoth mechanics.
Changing instances of this attack lightning to fire would mean to apply this to every instance...core and UMC. What prompted such a drastic change?

> Wouldn't it make more sense to change the icon? It could be something like sparks or stars instead.

Agreed.

Further arguments:
1. DM: changing fire to arcane gives Delfador a super buff for the mid-section to end of the campaign. You face undead a lot and they all have negative arcane resistance so the campaign's difficulty settings is just thrown out the window.
2. NR classic: giving that arcane powered rod makes the scenario very easy and also gives the player an advantage vs trolls in follow-up scenarios. **Won't impact NR-rework at all.**
3. Dead Water: this type swap makes the campaign easier on all difficulties....antagonists are undead primarily and they have negative arcane resistance.
4. World Conquest: this change has no value as storm trident is now a less-desired version of the staff of light artifact, and players lose out on a fire-ranged magical attack artifact.
5. HttT: Delfador has now arcane ranged...this makes scenarios such as _Valley of Death_, _Lost General_, _Choice must be made_, _Cliffs of Thora_, _Swamp of Dread_, _Underground channels_ way too easy now. `14` base + `1.50 * 14` = `21` and with 4 attacks and magical..that's enough to wipe out most enemies. On the other hand, the last scenarios of HttT can be slightly harder since loyalists have +20% arcane resistance.
So, you can see how _immense_ of an impact this will have on SP alone.

2022-09-02 05:20 UTC, Jonathan-Kelly commented
### Lore

Electrical injuries are more complicated than simple burn injuries. They necessarily cause deep, three dimensional injuries, rather than primarily affecting surface tissue like skin. Electricity has a particularly dramatic effect on the nervous system too. And thermally conductive does not equal electrically conductive. So if we are looking at this from a modern scientific standpoint, damage from fire and electricity cannot be lumped together any more than "blade" and "pierce".

If instead we look at it from a wesnothian perspective, essentially a classical/medieval perspective, phenomena like lightning would certainly be classified as arcane - not predictable or well understood by anyone except a very well informed few, Electrical arcing does not follow a straight, simple path; it can curve around a (less conductive) obstacle to hit someone hiding behind it, Which is precisely what the `magical` ability means in wesnoth parlance (i.e. unaffected by ordinary cover).

> but arcane damage is an abstract sort of "magic" thing, so it doesn't fit lightning at all in my opinion.

There are magical fire and cold attacks as well. Hot and cold are simply more accessible to a wesnothian understanding of the natural world. There is nothing to say arcane is "pure" magic whereas the fire and cold magics are somehow less so. The white mage's "lightbeam" may seem abstract to someone who has never heard of a photon before, but that does not make it any less physical or real.

### Balance

**Jinn** - We have many monsters with fire and impact attacks (strong v undead) but few with cold and pierce (strong v drakes). Changing its lightning attack to arcane is helpful in this regard.

**Elder Mage** - This is Level 5 unit but (like the Fire Dragon) it acts like a 3 or 4. It needs to act like the thing that it is - extremely powerful.

**Campaigns** - I agree that some gold adjustments may be needed for some scenarios. But we are only talking about one unit instance per campaign. One Delfador or one Storm Trident or one Rod of Justice for scenarios that involve armies of units almost as powerful. The one of a kind Delfador unit is weaker than the Arch Mages a player can train for themselves in the same campaign.

**World Conquest** - I am not really familiar with this yet. I assume the Sceptre of Fire is too powerful to be the magical fire weapon? Is there really no supplement for the trident that uses fireballs? If, for example, I switched the Rod of Justice over to fireballs could that fill this slot?

2022-09-02 08:59 UTC, stevecotton commented
There's a lot of lore based on arcane being a damage type that affects the magical or unnatural side of creatures. I'm against trying to squeeze electricity into that definition.

* If arcane has a special effect on the nervous system, as in the electricity lore, why do humans have a general resistance to it?
* White Mage description: "a potent ally against magical or unnatural things."
* Wose race-lore: "Due to their close connection with faerie, woses are particularly sensitive to the arcane."
* Various Elven race-lore would need to change, including that their units are generally vulnerable to it.
* Why would electricity be so good against skeletal undead?

The dictionary definition of arcane, "hidden or secret", doesn't help define why it does damage. At one stage in Wesnoth's history it was called "holy", sadly the commit message on 6c4a464877cf32281f107fe62394083b01284ac4 doesn't say why it was renamed.

If you push too much real-world physics into a fantasy world then does electromagnetism have to come too? Combine that with mages being able to summon electricity and the motor effect shouldn't take long to be discovered, after which dynamos should be coming along too.

2022-09-02 11:59 UTC, max-torch commented
Consider that many UMC content have already been carefully balanced and designed around this. This has the potential to ruin a lot of content or create a lot of work for a lot of people.

2022-09-02 15:17 UTC, knyghtmare commented
> ask is it rare in UMC?

Quite the opposite. It's very utilised. In LOTI, and other addons

A drastic change to just accommodate the level 5 Storm Daemon seems a bit too much. I think just swapping the icon for something "Arcane"-y or introducing a 7th damage type "electric/lightning" might as well resolve the matter.

2022-09-02 16:25 UTC, Jonathan-Kelly commented
I never expected this would be controversial. I am trying to understand if it is the changes that are the issue or just my failing to communicate the concept behind them at all well.

@stevecotton 
> If you push too much real-world physics into a fantasy world then does electromagnetism have to come too?

Discussing real-world physics was only to address the idea that lightning does `fire` damage. I agree that injecting too much science would be harmful.

> There's a lot of lore based on arcane being a damage type that affects the magical or unnatural side of creatures.

I agree. Though this change would only be to `magical` attacks, so it is left to the audience to decide if this is natural or supernatural lightning.

> At one stage in Wesnoth's history it was called "holy", sadly the commit message on https://github.com/wesnoth/wesnoth/commit/6c4a464877cf32281f107fe62394083b01284ac4 doesn't say why it was renamed.

If I recall correctly, the reason for the change was that undead mirror matches were very slow due to them having both cold focused attacks and cold resistance. The solution was to give undead a few powerful holy attacks, but that went against the lore of the time saying undead were specifically *un*holy. So the name was changed to arcane.

@max-torch and @knyghtmare 
> It's very utilised. In LOTI, and other addons

Which of the core changes cause problems for UMC? The core changes being:
* Jinn
* Elder Mage
* Storm Trident (never used in mainline, rewritten from scratch each campaign it appears in)

Or do you mean any use of the lightning bolt attack animation, in general?

2022-09-02 16:59 UTC, Discontinuum commented
I would rather change the icon for arcane somehow, to be honest, as folks above already proposed. Changing units stats just because of relatively recently introduced icons for damage types (which I don't like too much, to be honest, I would prefer the old way, text strings) - to me that's a strange direction of changes

2022-09-02 17:01 UTC, knyghtmare commented
> any use of the lightning bolt attack animation, in general?

What I meant was lightning being coded as a `type=fire`. It's been like this for so long that either it's `type=fire` or `type=electric` (only 2 addons). So, core changing lightning from fire to arcane would/can cause a tidal wave of new/current/returning player confusion in the inconsistencies they will see in the next stable.
A thing that's stayed so long and constant is supposed to exhibit greater resistance to change. QAM 101

> Storm Trident (never used in mainline, rewritten from scratch each campaign it appears in)

That might be a bug since if a core macro exists why should mainline works re-define their own versions...?

Also, I think the arguments are mostly on **"what lightning should be in wesnoth"**? 

> World Conquest - I am not really familiar with this yet. I assume the Sceptre of Fire is too powerful to be the magical fire weapon? Is there really no supplement for the trident that uses fireballs? If, for example, I switched the Rod of Justice over to fireballs could that fill this slot?

The SoF in WC might be overkill. 14-4 fire ranged magical...I guess the WC artifact DLC pack has an close equivalent in it to rival the storm trident. You can view the lists to see which artifact does what. There is ranged ice (frost bow), ranged arcane (Staff of light), and ranged fire (storm trident). So, swapping the storm trident for some fire amulet to throw fire might one solution.

2022-09-02 22:26 UTC, CelticMinstrel commented
> I would rather change the icon for arcane somehow, to be honest, as folks above already proposed.

If this is being done because the icon for arcane is a lightning bolt, then I vote to just change it to a pentacle or ankh instead.

2022-09-13 19:39 UTC, Jonathan-Kelly commented
@CelticMinstrel
> If this is being done because the icon for arcane is a lightning bolt,

The icon is one of a few reasons.

This change also gives the impressive and distinctive _looking_ lightning attack something to _functionally_ distinguish it from the various fireball attacks, as @nemaara mentioned.

And this better distinguishes arcane from the other attack types. Right now, arcane is almost a miscellaneous category, originally created by lumping various cold attacks (like shadow wave and faerie fire) together with a few holy ones. It could really benefit from having a common theme or element. By including lightning we have a few of these to choose from - luminous, energetic and/or celestial (as in cast down from the sky or aether).

Lastly, while lightning does transmit heat, being struck by lightning is much more harmful in other ways.

@knyghtmare
> That might be a bug since if a core macro exists why should mainline works re-define their own versions...?

> The SoF in WC might be overkill. 14-4 fire ranged magical...I guess the WC artifact DLC pack has an close equivalent in it to rival the storm trident. You can view the lists to see which artifact does what. There is ranged ice (frost bow), ranged arcane (Staff of light), and ranged fire (storm trident). So, swapping the storm trident for some fire amulet to throw fire might one solution.

Looks like there is another bug: the WC Storm Trident does 17-2 damage while all other Storm Trident instances use 14-2. So swapping out WC's Trident for something else may be a good idea generally.

2022-09-13 23:02 UTC, knyghtmare commented
> Looks like there is another bug: the WC Storm Trident does 17-2 damage while all other Storm Trident instances use 14-2. So swapping out WC's Trident for something else may be a good idea generally.

No. This does not count as a bug. The magic attacks artifacts are all in the total damage range of ~30-35 so 17-2 fits. while is 14-2 is too low. Setting it to 14-2 will upset players a lot.
 ~~I should also mention that they are dissatisfied due to our lack of testing of WC (it's a bit buggy right now) before shipping it with the current stable and I am not in-line with upsetting them any further.~~

2022-09-14 16:20 UTC, Jonathan-Kelly commented
@CelticMinstrel
> I'm not sure on what basis you claim that shadow wave and faerie fire are cold attacks. They have been arcane for as long as I've played Wesnoth,

They were originally [cold attacks up to version 1.2](https://units.wesnoth.org/1.2/Elvish_Sylph.html) then switched to [arcane for version 1.4](https://units.wesnoth.org/1.4/C/Elvish%20Sylph.html). There was a theme of faerie things running opposite to mundane expectations. The elves closest to the faerie world (like the shyde) start to age in reverse, the lightest "faerie touch" from a single finger strikes with the force of a mace, and "faerie fire" freezes rather than burns.

It was some well thought lore handled with appropriate subtlety.

Whereas the switch to arcane was motivated not by lore but by a balance necessity. Those of us around in those early days hated undead mirror matches for good reason; undead used cold for their most important attacks yet were largely immune to it themselves, leading to very long and tedious stalemates. So various cold and "holy" attacks were switched to arcane to solve the problem.

But from a lore perspective, the change was an afterthought which left arcane as the miscellaneous magic category.

> On the contrary, adding lightning to arcane makes it _more_ of a grab bag than it already is. Most of the existing attacks that use arcane damage are conceptually either "holy" or "unholy". Those that don't fit that classification are "generic energy" (silver mage, runesmith, arcanister) or "nature energy" (faerie fire).

The way to fix the grab bag is to pick a single common element or theme that runs through all these things (we can exclude the silver mage and runesmith line since they lack arcane attacks). The three that I could think of are: Light, Sky (celestial, aether) and Energy (powerful but intangible things lacking material or substance). Your suggestion of Nature works equally well.

> Lightning doesn't fit well into _any_ of those four categories; you could argue it's "nature energy", but there isn't really any similarity between lightning and faerie fire.

They are both very luminous, fitting into a theme of light.

They are both products of the pure natural world, fitting into a theme of nature energy.

If we can agree that faerie fire has a cloud or mist like appearance, then both can be related to the sky, clouds, weather, aether. The white mage's "lightbeam" (its animation depicting something like a [Sunbeam](https://en.wikipedia.org/wiki/Sunbeam)) also fits this.

In any case, shadow wave is a twisting, inversion or corruption of whichever theme. Shadows are a blocking of light and (at least a partial) blocking of the sky. And unlife turns death into life (and often life into death) thereby going against nature.

@knyghtmare
> The magic attacks artifacts are all in the total damage range of ~30-35 so 17-2 fits. while is 14-2 is too low. Setting it to 14-2 will upset players a lot.

I meant you could swap out the Storm Trident for the Fire Amulet like you mentioned earlier. Since the Amulet (unlike the Trident) never appears in mainline, you could assign to it whatever statistics you need. The lore might be that it is made from one of the shards cleaved from the Ruby of Fire when Thursagan crafted the SoF (which is why it is less powerful than the SoF).

2022-09-15 00:51 UTC, CelticMinstrel commented
> we can exclude the silver mage and runesmith line since they lack arcane attacks

Huh. I was _sure_ I'd seen a "magic missile" type attack on some unit somewhere that was arcane, and I thought it was the silver mage, but the silver mage's attack is fire. That honestly doesn't make much sense – unlike the other mages, it doesn't _look_ like fire at all.

I guess I got confused on the runesmith line. They are magical but not arcane, apparently.

> They were originally [cold attacks up to version 1.2](https://units.wesnoth.org/1.2/Elvish_Sylph.html) then switched to [arcane for version 1.4](https://units.wesnoth.org/1.4/C/Elvish%20Sylph.html).

1.2 is so long ago that I'm not really inclined to consider anything from back then as relevant.

> The way to fix the grab bag is to pick a single common element or theme that runs through all these things

That doesn't really change that it's a grab bag, honestly. You're taking the grab bag and trying to unify it under a single explanation, but it's still a grab bag. And unifying it is a lot easier without throwing lightning in the mix.

2022-09-16 16:52 UTC, soliton- commented
Explanation for holy damage changes (arcane wasn't settled on yet): https://web.archive.org/web/20170227211104/https://mail.gna.org/public/wesnoth-dev/2007-02/msg00001.html

2022-09-17 01:13 UTC, knyghtmare commented
> I meant you could swap out the Storm Trident for the Fire Amulet like you mentioned earlier. Since the Amulet (unlike the Trident) never appears in mainline, you could assign to it whatever statistics you need. The lore might be that it is made from one of the shards cleaved from the Ruby of Fire when Thursagan crafted the SoF (which is why it is less powerful than the SoF).

This should be pulled out and listed as a separate FR.

> It gets worse. The "magic missile" is used by the L1 Mage, then it switches to "fireball" for the L2 Red Mage, and finally it switches back to "magic missile" again for the L3 Silver Mage. That is all one advancement line and all said attacks do fire damage.

It is what it is. It's always been like that. _Magic Missile_ might be present in 2 units right now: Mage and Silver Mage.

2022-09-17 01:39 UTC, CelticMinstrel commented
> It gets worse. The "magic missile" is used by the L1 Mage, then it switches to "fireball" for the L2 Red Mage, and finally it switches back to "magic missile" again for the L3 Silver Mage. That is all one advancement line and all said attacks do fire damage.

I noticed that too. It _is_ a little strange, but you can explain it in lore by all mages knowing both fireball and magic missile but they just use the one they're most skilled at.

2022-09-19 10:56 UTC, stevecotton commented
> They are both very luminous, fitting into a theme of light.
> 
> They are both products of the pure natural world, fitting into a theme of nature energy.
> 
> If we can agree that faerie fire has a cloud or mist like appearance, then both can be related to the sky, clouds, weather, aether. The white mage's "lightbeam" (its animation depicting something like a [Sunbeam](https://en.wikipedia.org/wiki/Sunbeam)) also fits this.

"Aether" is basically the same as "arcane", in that we don't have a common understanding of what it is, so it's still whatever the reader wants it to be. Excluding that one, none of these themes would fit with the Ghost line's arcane attacks.

> In any case, shadow wave is a twisting, inversion or corruption of whichever theme. Shadows are a blocking of light and (at least a partial) blocking of the sky. And unlife turns death into life (and often life into death) thereby going against nature.

When "fire" and "cold" are separate and opposite types, it seems bad to select a theme and then say that opposites are collected together in order to include the Necromancer and Ghost lines' attacks into the same category. IMO it's better to have the current hazy definition of "arcane", rather than to try to fit an ill-fitting theme on it.

> Storm Trident (never used in mainline, rewritten from scratch each campaign it appears in)

* HttT uses the core macro.
* TRoW uses the core macro. It also has a cut & paste for Lord Typhon's trident, as he spawns already carrying it.
* DiD Why doesn't Malin take the trident that's in S03 with him? Anyway, it doesn't use the core macro because no unit can pick it up and use it as an attack.
* Dead_Water uses a campaign-specific set of events for digging it up, because it's half-buried in mud. It also needs dialogue specific to bats which are likely to be used as scouts.

2022-09-19 23:29 UTC, Jonathan-Kelly commented
> Excluding that one, none of these themes would fit with the Ghost line's arcane attacks.

Hmm, that is true. It has "wail" instead of the "shadow wave" for its arcane attack.

> When "fire" and "cold" are separate and opposite types, it seems bad to select a theme and then say that opposites are collected together in order to include the Necromancer and Ghost lines' attacks into the same category.

That is a fair point.

So to clarify, @stevecotton are you opposed to lightning being classed as `arcane` rather than `fire`, or to put it another way, are you opposed to magical creatures having a mysterious vulnerability to lightning?

---

@knyghtmare
> I guess the WC artifact DLC pack has an close equivalent in it to rival the storm trident. You can view the lists to see which artifact does what. There is ranged ice (frost bow), ranged arcane (Staff of light), and ranged fire (storm trident). So, swapping the storm trident for some fire amulet to throw fire might one solution.

> This should be pulled out and listed as a separate FR.

Alright, where do I find this world conquest artifact pack? Is it listed under a different name in the add-ons servers or is it on github?

2022-09-20 07:09 UTC, stevecotton commented
> So to clarify, @stevecotton are you opposed to lightning being classed as `arcane` rather than `fire`, or to put it another way, are you opposed to magical creatures having a mysterious vulnerability to lightning?

I'm opposed to the attack of the storm tridents, and HttT's Delfador being classed as `arcane`. However, the second part of your question made me think more about the lore, and about what would get called "lightning".

The storm tridents' powers are unaffected by being underground, so they're not calling energy from the sky, regardless of the attack's images. They don't cause damage to nearby units (even in water), so there isn't a discharge path from the target. Instead of making it an electrical attack, I think it's less of a handwave to say that it's really a powerful fireball attack that due to being white-hot and loud became known as "lightning".

The lore of Delfador's lightning is messy - he gets a legendary storm-staff in the Land of the Dead; but when Asheviere betrays Gerard II, Delfador leaves his staff for her to take`*`. It's in-character for him to say that the staff was too powerful to pass to another mage, and to have disenchanted it in the meantime. Asheviere's attack in the finale is cold-based, so she's not using the storm-staff. However this means that in HttT he's casting the lightning himself rather than using the staff.

HttT is for new players and includes storm tridents, so I'd be opposed to giving Delfador an attack that looks like the storm trident but has a different damage type. Lore-wise, for HttT I suggest that his attack was learnt from studying the legendary staff, or studying a storm trident, or from books about the history of the storm tridents.

`*` Intro to HttT, "In the end Delfador’s men were defeated and routed, but Asheviere found her son’s lifeless body, fixed to the ground by the great mage’s staff."

2022-09-20 13:48 UTC, max-torch commented
I just want to commend the fact that @stevecotton cited a plot hole, regarding delfador's staff and his lightning attack, as well as the solution to said plot hole. Bravo! Saying he studied or practiced the lightning attack sufficiently, such that he didn't need the staff to cast it, sounds good.

2022-09-20 14:32 UTC, knyghtmare commented
>> I guess the WC artifact DLC pack has an close equivalent in it to rival the storm trident. You can view the lists to see which artifact does what. There is ranged ice (frost bow), ranged arcane (Staff of light), and ranged fire (storm trident). So, swapping the storm trident for some fire amulet to throw fire might one solution.

>> This should be pulled out and listed as a separate FR.

> Alright, where do I find this world conquest artifact pack? Is it listed under a different name in the add-ons servers or is it on github?

@Jonathan-Kelly 

The _Legends Conquest_ Artifact Modification is shipped with _War of Legends_ MP Era add-on which has its repo linked to my profile.

> DiD Why doesn't Malin take the trident that's in S03 with him? Anyway, it doesn't use the core macro because no unit can pick it up and use it as an attack.

> I'm opposed to the attack of the storm tridents, and HttT's Delfador being classed as arcane. However, the second part of your question made me think more about the lore, and about what would get called "lightning".

@stevecotton  It's part of the S3 puzzle. The mud crawler one, and I have to clarify...that puzzles uses the establiahed logic that lightning is a **fire** attack. Which supports are your argument.


> The lore of Delfador's lightning is messy - he gets a legendary storm-staff in the Land of the Dead; but when Asheviere betrays Gerard II, Delfador leaves his staff for her to take*. It's in-character for him to say that the staff was too powerful to pass to another mage, and to have disenchanted it in the meantime. Asheviere's attack in the finale is cold-based, so she's not using the storm-staff. However this means that in HttT he's casting the lightning himself rather than using the staff.
> I just want to commend the fact that @stevecotton cited a plot hole, regarding delfador's staff and his lightning attack, as well as the solution to said plot hole. Bravo! Saying he studied or practiced the lightning attack sufficiently, such that he no longer needed the staff to cast it, sounds good.

I did not know there was a plot hole in HttT as huge as this...might be years of not paying attention to the static story texts. This must be fixed.

https://github.com/wesnoth/wesnoth/blob/d01aabc81fbbba63883195c75293a96a5a4eb63b/data/campaigns/Heir_To_The_Throne/scenarios/24_Battle_for_Wesnoth.cfg#L401-L404

As this piece of dialogue says he still has it...which he shouldn't anymore.

2022-09-20 15:34 UTC, Discontinuum commented
>  but Asheviere found her son’s lifeless body, fixed to the ground by the great mage’s staff

It may be another ordinary staff, not the staff of An-Usrukhar. Who said that Delfador necessarily used his premier staff in every battle?

2022-09-20 16:15 UTC, Jonathan-Kelly commented
@stevecotton
> The storm tridents' powers are unaffected by being underground, so they're not calling energy from the sky, regardless of the attack's images.

Hmm, Delfador's attack is also seen being used underground. Actually, so too does the arcane `lightbeam` attack of the White Mage line. Perhaps the way to explain these attacks working underground despite their graphical appearance of being "called down" from the sky is through the use of teleportation / magic portals like those used in TRoW and DM? In other words, a portal connecting to the inside of a lightning storm (or the sun) is opened some distance overhead the target.

Otherwise, regardless of the damage type, there is no explanation for why the attack comes down from the cave ceiling rather than from the attacker?

> HttT is for new players and includes storm tridents, so I'd be opposed to giving Delfador an attack that looks like the storm trident but has a different damage type.

To clarify, this PR would keep both attacks having the same attack type as each other. I agree separating them would be a bad idea, since they share the same graphics (though I suppose there is color grading).

@knyghtmare 
> The _Legends Conquest_ Artifact Modification is shipped with _War of Legends_ MP Era add-on which has its repo linked to my profile.

Thanks, I will check that out and start familiarizing myself with WC.

2022-09-21 12:06 UTC, stevecotton commented
Teleportation and portals (even if they just transport energy) seem to likely to open separate plot holes - AFAICS a common feature of Wesnoth's plotlines is that news doesn't travel fast - so when a border post is lost, other people aren't aware until something else causes them to investigate.

If every white mage is routinely opening energy portals, then they should be set up a telecommunications network and early-warning system. The same applies to the amulet in AToTB's backstory, but that could just be [replaced by calling for help with a signal fire](https://r.wesnoth.org/p669889).

The portal that the orcs came to the green isle through could get handwaved with a "tons of liches involved, possibly involved portals to the Land of the Dead, anyone doing any research on it will be considered to be a necromancer". No idea how silver mages don't get used as couriers though.

@nemaara please would you comment?

2022-09-22 20:16 UTC, Jonathan-Kelly commented
@CelticMinstrel 
> And don't forget that teleportation is the silver mage's specialty.

It may be more accurate to say _tactical_ teleportation is their specialty since we see powerful liches and necromancers creating much larger portals to move entire armies over potentially greater distances than a silver mage can manage (in a single go).

@stevecotton 
> No idea how silver mages don't get used as couriers though.

Well, they may be unwilling. [The silver order is highly secretive](https://units.wesnoth.org/1.16/mainline/en_US/Silver%20Mage.html) and setting up the necessary network of village portals could expose their coveted teleportation technique to study by other mages. Perhaps after a battle they participated in is won, they even go so far as to disenchant or collect all the portal talismans placed in allied villages, so nothing is left for others to discover.

---

Anyway, this discussion has been useful for documenting several inconsistencies for future improvements:
* Delfador's very special staff being discarded in the beginning of HttT yet remaining with him.
* World Conquest giving a mermish exclusive artifact to any race and using stats inconsistent with elsewhere,
* Attacks which are visibly "called down" from the sky being used underground.
* Magic missile and fireball swapping places back and forth in one advancement line.
* Arcane being a handwavium embroidered grab bag.

But for the purpose of this PR, we may need to focus on just the core question - should lightning be treated as fire or as something more _arcane_? Is lightning a mysterious and unpredictable force of nature which unnatural things should fear? Or is it simply very hot?

2022-09-23 05:08 UTC, CelticMinstrel commented
> Perhaps after a battle they participated in is won, they even go so far as to disenchant or collect all the portal talismans placed in allied villages, so nothing is left for others to discover.

I'm not sure why you'd even assume their teleportation relies on talismans at all. But the general point of them being unwilling to perform as a courier does make sense.

> But for the purpose of this PR, we may need to focus on just the core question - should lightning be treated as fire or as something more _arcane_? Is lightning a mysterious and unpredictable force of nature which unnatural things should fear? Or is it simply very hot?

I still think the concept of it just being very hot is sufficient. Sure, it's not scientifically accurate, but that really has no relevance to Wesnoth.

2022-09-24 00:04 UTC, nemaara commented
> Teleportation and portals (even if they just transport energy) seem to likely to open separate plot holes - AFAICS a common feature of Wesnoth's plotlines is that news doesn't travel fast - so when a border post is lost, other people aren't aware until something else causes them to investigate.
> 
> If every white mage is routinely opening energy portals, then they should be set up a telecommunications network and early-warning system. The same applies to the amulet in AToTB's backstory, but that could just be [replaced by calling for help with a signal fire](https://r.wesnoth.org/p669889).
> 
> The portal that the orcs came to the green isle through could get handwaved with a "tons of liches involved, possibly involved portals to the Land of the Dead, anyone doing any research on it will be considered to be a necromancer". No idea how silver mages don't get used as couriers though.
> 
> @nemaara please would you comment?

I agree with Jonathan Kelly's comment on the silver mages. On the orc side, you've provided a good theory as well, although I'd say that can stay a theory at a moment. More discussion on that might be not exactly relevant to this topic so I don't know if we should talk more about that or just stay focused on lightning itself.

I've approved this PR because I personally am fine with this change, but I won't be merging unless a few others have been convinced as well. If there are too many people unconvinced even after explanation, we can go ahead and close this PR too.

2022-09-24 01:08 UTC, Jonathan-Kelly commented
Well, it looks like the idea has turned out to be thoroughly unpopular enough already, so I will close.

2022-09-24 01:08 UTC, closed without merging