UTBS Alien Minion and Alien Spire XP reduced
wesnoth/wesnoth pull request #7339
Opened 2023-01-29 18:20 UTC by Toranks

![imagen](https://user-images.githubusercontent.com/40789364/215347397-c8c6c785-b52f-45c4-a1f4-ed974a017554.png)

All the alien units have the same experience, resulting in this disproportion, and it looks pretty ugly.

I can change the ratio of the experience bar with xp_bar_scaling, but reducing the experience is the best option, it does not affect the balance since they are low health units, it is very almost impossible for them to level up.

2023-01-29 18:20 UTC, Toranks commented
With the changes
![imagen](https://user-images.githubusercontent.com/40789364/215347560-4c89075c-25d4-4277-a03b-331138fabba5.png)

2023-01-29 18:23 UTC, Pentarctagon commented
I think that should've been fixed more generally already with #7293 ?

2023-01-29 18:30 UTC, Toranks commented
Partially, that only limits the maximum length. An experience bar many times longer than HP still looks ugly for a "minion" unit that will never advance.
If you really need an unit with a lot of experience, xp_bar_scaling would be another option.

2023-01-29 18:54 UTC, stevecotton commented
Should we rename this issue to avoid spoilers? Maybe "UTBS S12: Minion and Spire XP reduced"?

2023-01-29 18:57 UTC, stevecotton commented
50 XP seems a bit low, given that in this scenario they might be killing L3 units after the main attacks have damaged them.

I'm in two minds about the long bars - they do communicate clearly that these units aren't intended to level.

2023-01-29 21:21 UTC, CelticMinstrel commented
I wonder what happens if you set `experience=0` in the unit type config, along with no advancements at all (including no AMLA)…

2023-01-30 04:25 UTC, Wedge009 commented
Out of curiosity, I set Grand Knight (final advancement) to `experience=0` and removed `{AMLA_DEFAULT}` and debug-created one in a game. It shows XP as - in the side-bar, and the unit has no XP bar, only HP. Killing a unit appears to have no effect and I didn't see any error messages in the log. So it appears the engine handles this situation fine, no division-by-zero or anything like that.

2023-01-30 05:32 UTC, nemaara approved these changes

2023-01-30 06:56 UTC, CelticMinstrel commented
The reason I mentioned it is because I thought that, if correctly handled, this might be a good place to do that.

2023-01-30 07:15 UTC, Toranks commented
I've tested and what @Wedge009 says works. Changing experience to 0 doesn't work by itself, it only changes experience to 1 and can levelup multiple times with just 1 attack. But if I remove {AMLA_DEFAULT} too, the experience changes to "-" and never levelup.
![imagen](https://user-images.githubusercontent.com/40789364/215411397-a73f1be2-d2a2-4849-b16d-34f212c2af54.png)

2023-01-31 05:10 UTC, stevecotton requested changes
If you're relying on edge-case behavior then it's good to have a unit test, and I think it's mandatory in this case. If the behavior changes then the minions might get a levelup and full-heal after each combat, but that wouldn't be noticed at the time of the engine change, and players might assume it's an intended quirk of this scenario.

The current HOWTO for writing unit tests is here: https://github.com/wesnoth/wesnoth/issues/7159#issuecomment-1399414492

2023-01-31 06:11 UTC, Toranks commented
I already sent a PR with a test before, I'll use the template.
I imagine changing Alice's and Bob's experience to 0, and deleting Bob's AMLA DEFAULT but not Alice's.
They then fight each other.
The result should be that Alice levels up as many times as Bob's levels, and Bob stays the same.
Do you think a test like this would do the work to cover both cases?

2023-01-31 06:32 UTC, stevecotton commented
Harm Bob first, and check that he doesn't heal.

I guess Alice will only go up once, and then have some xp left over afterwards (because the level-up will probably give Alice a higher max xp before the next level).

2023-02-02 06:11 UTC, stevecotton commented
> I've tested and what @Wedge009 says works. Changing experience to 0 doesn't work by itself, it only changes experience to 1 and can levelup multiple times with just 1 attack. But if I remove {AMLA_DEFAULT} too, the experience changes to "-" and never levelup.

Thanks for writing the unit test. Based on experimenting with it, it seems that changing `max_experience` isn't necessary - just removing the advancement hides the xp bar and makes the sidebar show "-", even when `:inspect` shows that the unit has 1/42 xp.

If we don't need `max_experience=0`, then I'd prefer to avoid it. Looking in the C++, it looks like would be a division-by-zero error if drawer.cpp circa line 414's `double filled = static_cast<double>(experience) / static_cast<double>(max_experience);` was reachable with `max_experience==0`. There also seems to be a sanity check ensuring that doesn't happen, with `unit::init` enforcing a minimum of 1.

2023-02-10 22:06 UTC, Toranks commented
I have a change request here by @stevecotton , which was to do the unit test before relying on the experience behaviour that changes the PR. The unit test was already merged on master, so I assume I don't need to do anything else here, right?

2023-02-11 03:11 UTC, stevecotton commented
Based on the tests, removing the `{AMLA_DEFAULT}` hides the xp bars, without needing to reduce the experience. Just in case someone changes the behavior, I'd prefer to have either:

* high experience numbers in UtBS S12, even though they're hidden, or
* a comment in the zero_experience test noting that the behavior is used in UtBS S12.

My reasoning is that someone may change the behavior (and the test) without someone else spotting the bug in S12 afterwards. In either case, it would be good to have a comment in the UtBS files about hiding the XP.

2023-02-14 12:35 UTC, Toranks commented
I chose the first option. In case someone used the experience for something with mods or addons. I use the original exp number, which is already quite high.

2023-02-15 08:09 UTC, merged