WC II - Typo and translatability of Difficulty and Version
wesnoth/wesnoth pull request #7795
Opened 2023-07-15 02:20 UTC by Toranks

![imagen](https://github.com/wesnoth/wesnoth/assets/40789364/fb9e50a2-8f18-444a-ba84-12350d7725ef)

It should be backported too

2023-07-15 03:55 UTC, Wedge009 commented
Regarding back-port, I seem to recall a change in rules (or perhaps, an establishment of a standard set of rules) regarding string changes on stable branches recently. But 'Difficulty: ' and 'Version: ' are both existing translated strings (specifically, `wesnoth-lib` domain) so I think it should be fine to back-port.

2023-07-15 03:56 UTC, Wedge009 approved these changes

2023-07-15 09:16 UTC, stevecotton commented
To use the existing strings in 1.16, this ought to look up those strings in the `wesnoth-lib` textdomain. Just create a second local variable similar to the existing `local _ = wesnoth.textdomain 'wesnoth-wc'` a few lines above the one that's changed.

2023-07-15 16:38 UTC, Toranks commented
Take a look at the change, to see if I've done it correctly.

2023-07-15 17:45 UTC, Pentarctagon commented
That'd only be needed for 1.16 though, right?

2023-07-15 17:54 UTC, Toranks commented
> That'd only be needed for 1.16 though, right?

Why? It's for both

2023-07-15 18:58 UTC, stevecotton commented
I think we should merge this. While 1.17 doesn't need to avoid adding strings to `wesnoth-wc`, it's easier to keep track of backports if the commit is the same in both places.

2023-07-15 21:36 UTC, gfgtdf commented
I wonder whether there is still any reason to have the version there, it used to be the add-ons version but since it was Mainlined there is no such thing as "add-on version"

2023-07-17 08:44 UTC, soliton- commented
Yeah, the version part should just be removed.

2023-07-17 09:13 UTC, Toranks commented
Do you think it is acceptable to comment on it, so that it is known that it was there? Maybe for debugging purpose

2023-07-17 09:45 UTC, Wedge009 commented
Heh, couldn't work out how to retract approvals, but you updated it already anyway.

2023-07-17 11:50 UTC, gfgtdf commented
It looks to me like you are just deleting the version string variable without changing the code that actually uses it

2023-07-17 12:44 UTC, Toranks commented
Difficulty still uses the code

2023-07-17 13:56 UTC, stevecotton requested changes
> It looks to me like you are just deleting the version string variable without changing the code that actually uses it

This. Look at line 31 of the file (same line number in both the old and new versions).

2023-07-17 19:10 UTC, stevecotton reviewed
I'm wondering if the other two instances of `wc2_host_version` can be removed too, but this PR now looks good to me. @Hejnewar would be the person who needs to approve it though.

2023-07-17 20:22 UTC, merged