Dragons!
wesnoth/wesnoth pull request #7827
Opened 2023-08-02 19:52 UTC by Hejnewar

As we all know dragons are weak. 

These changes are here to help with that a bit. 

Fire Dragon - hp changed form 101 to 500, cold resistance changed from -50% to 10%, 14-4 fire breath changed to 14-6, bite changed from 21-2 to 21-4, tail changed from 24-1 to 24-3, xp changed from 250 to 500, cost changed form 100 to 1297g, leadership removed. (Dont approach without at least 7 ancient liches. It bites.)
Skeletal dragon - hp changed from 86 to 171, jaw changed from 10-4 to 17-4, claws changed from 25-2 to 24-3, cost changed from 100 to 297. 

This is a separate issue from monsters balance pass because Draconic weakness is a long standing issue that sparks discussion (im knida counting on that) (also I didnt finish monsters and felt like this PR).

2023-08-02 19:58 UTC, knyghtmare reviewed
Fix #5703 while you are at it?

2023-08-02 20:06 UTC, Hejnewar commented
Is there skeletal tail whip attack icon? 
Too big to submerge.
Resistances can be fixed easily. 
Im torn of the dundead drag flying, I mean imo it could fly. 

Ah also, if possible I would like fire drag to have ray on its breath attack. :P

2023-08-02 20:09 UTC, knyghtmare commented
> Ah also, if possible I would like fire drag to have ray on its breath attack. :P

if you're going extreme, consider _intense_ weapon special. _inflictes enemy with burn status. 10HP loss/turn and can kill._
Okay, maybe too extreme....way too much.

> Is there skeletal tail whip attack icon?
> Too big to submerge.
> Resistances can be fixed easily.
> Im torn of the dundead drag flying, I mean imo it could fly.

Hmm, just adjusting the resistances is okay. That was the biggest reason for the bug opening.

2023-08-02 21:56 UTC, Dalas121 commented
If you're modifying the skeletal dragon, I suggest adding the terror aura (anti-leadership in a 2-hex radius) from EI #7815.  Should probably also nerf its recruits in that scenario so the AI's overall power-level stays similar.

(also I support knyghtmare's suggestions to give the fire dragon some kind of unique ability, instead of being a big sack of hp)

2023-08-02 22:55 UTC, cooljeanius commented
This is going to require some rebalancing of campaigns that feature them.

2023-08-02 23:21 UTC, Pentarctagon commented
It's also the boss of Dark Forecast, I think?

2023-08-02 23:25 UTC, nemaara requested changes
Finally, some real dragons instead of those weird weak things we used to have. On the other hand, this will break some UMC and mainline. Like egallager said, we at least need to fix the mainline campaigns so they're playable. This isn't a ton of work, but it does need to be included in this PR. I can help on that sometime, or Hejne or anyone else can propose ways to balance it.

Fire Dragon:
Descent into Darkness S9
Sceptre of Fire S8
The Rise of Wesnoth S17a
Winds of Fate S9
Dark Forecast (MP)

Skeletal Dragon:
Descent into Darkness S9
Eastern Invasion (revised) S14
Wilderlands (MP)

2023-08-03 00:12 UTC, CelticMinstrel commented
I think the only thing I really don't like here is the removal of leadership. I'm not too happy about removing cold as a weakness either.

2023-08-03 09:29 UTC, Hejnewar commented
> If you're modifying the skeletal dragon, I suggest adding the terror aura (anti-leadership in a 2-hex radius) from EI https://github.com/wesnoth/wesnoth/pull/7815. Should probably also nerf its recruits in that scenario so the AI's overall power-level stays similar.

Im generally unsure about abilities for such monesters. 

> I support knyghtmare's suggestions to give the fire dragon some kind of unique ability, instead of being just a big (albeit VERY big) sack of hp.

Similar here, I would rather not give the drags too much personality, having something that is just natural for them would be fine tho.

> I love the specificity of 1297g. 1300g would clearly be too expensive 😁

Yeah it would clearly be imba at 1300g. 

> Finally, some real dragons instead of those weird weak things we used to have. On the other hand, this will break some UMC and mainline. Like egallager said, we at least need to fix the mainline campaigns so they're playable. This isn't a ton of work, but it does need to be included in this PR. I can help on that sometime, or Hejne or anyone else can propose ways to balance it.

Im already breaking like a lot with my other already in game PRs in some campaigns so this doesnt make me worry too much. :P Actually it is perfect time for such changes.

> I think the only thing I really don't like here is the removal of leadership. I'm not too happy about removing cold as a weakness either.

I dont like leadership because it gives drag too much personality, like does every drag learn how to command armies from very young age? Are dragons smarter than every other race that we know of so far? I dont agree with people saying that dragons command thru fear.

Cold resistance is more complicated, I could give drag some cold vulnerability, but my thought process was that it is so hot that cold attacks weaken before they even hit the dragon. Maybe Im fantasising a bit too much.

2023-08-03 13:32 UTC, CelticMinstrel commented
> Similar here, I would rather not give the drags too much personality, having something that is just natural for them would be fine tho.

I think a fire breath that can hit more than one unit might be appropriate. Perhaps it conceptually travels for two or three hexes, halving the damage with each hex, and each unit in the line of fire has a separate chance to avoid it.

Or perhaps something like the merman brawler's stun attack.

> I dont like leadership because it gives drag too much personality, like does every drag learn how to command armies from very young age? Are dragons smarter than every other race that we know of so far? I dont agree with people saying that dragons command thru fear.

I kind of get your point. Personally I think the point of the leadership is that they command through not fear but awe and reverence, which might imply a leadership filtered to only affect drakes. The main reason I don't like removing it is because it seems cool and is the only instance of a level 5 leadership in the game, rather than because I think it makes for great lore (though it doesn't make for terrible lore in my opinion).

2023-08-03 13:53 UTC, cooljeanius commented
> I kind of get your point. Personally I think the point of the leadership is that they command through not fear but awe and reverence, which might imply a leadership filtered to only affect drakes.

Maybe drakes, and also any other units with a fire-type attack?

2023-08-03 13:55 UTC, Dalas121 commented
> I'm generally unsure about abilities for such monesters.

> Similar here, I would rather not give the drags too much personality, having something that is just natural for them would be fine tho.

> I dont like leadership because it gives drag too much personality, like does every drag learn how to command armies from very young age?

That makes sense; I think I agree with you.  Special abilities are probably better added on a case-by-case basis, to emphasize that each and every dragon is unique, rather than dumping the same ability on all of them.

> Cold resistance is more complicated, I could give drag some cold vulnerability, but my thought process was that it is so hot that cold attacks weaken before they even hit the dragon. Maybe Im fantasising a bit too much.
I can see either way.  IMO we should go with whatever makes the most sense for balance.

2023-08-03 14:35 UTC, Jonathan-Kelly commented
I really love CelticMinstrel's idea of giving the dragon one or two area of effect attacks (aka AoE or splash damage). Give its fire breath attack the ability to hit all the units around the one being directly attacked. The damage done to them could be half or full. The tail whip attack could have the same ability.

Seeing swathes of units get bathed in fire would be epic. An end in itself.

But this would also help dissuade a strategy of crowding the dragon with 3-6 expendable meat shield units so that it becomes immobilized. And it prevents having battles... drag on... for too long because a dragon can only attack one opponent per turn.

Additional suggestions:

- Fire breath does 21-4 instead of 14-6 to better match the "giant exploding fireball" attack animation.
- Frost breath for skeletal dragon.
- Flight or Submerge for skeletal dragon (oceans are quite a lot deeper than 10 meters so it surely _can_ submerge).  :p

2023-08-03 15:00 UTC, Hejnewar commented
> Here's a proposal: dragons are extremely rare in mainline, and are more-or-less boss monsters whenever they show up. What about leaving the generic "fire dragon" and "skeletal dragon" unchanged (so add-ons are unaffected), but customizing balance for each mainline dragon separately.

I would say that better baseline, especially when it comes to breath and hp would still be nice. Another thing that I think would be nice would be separate sprites but that is not something to count on, and there are probably better uses of artists time.

> I really love CelticMinstrel's idea of giving the dragon one or two area of effect attacks (aka AoE or splash damage). Give its fire breath attack the ability to hit all the units around the one being directly attacked. The damage done to them could be half or full. The tail whip attack could have the same ability.

Hey hey, I started that. :P Tho ye many people can have silimar ideas, I can mostly do that ability but I dont feel confident in creating the "each unit in the line of fire has a separate chance to avoid it" so that I would need to get some help with, or someone can just provide the ability(ies). :P

> Fire breath does 21-4 instead of 14-6 to better match the "giant exploding fireball" attack animation.

I agree I was actually thinking about that myself. 

> Frost breath for skeletal dragon.

Idk. 

> Flight or Submerge for skeletal dragon (oceans are quite a lot deeper than 10 meters so it surely can submerge). :p

They fly already.

2023-08-03 18:15 UTC, CelticMinstrel commented
> Here's a proposal: dragons are extremely rare in mainline, and are more-or-less boss monsters whenever they show up. What about leaving the generic "fire dragon" and "skeletal dragon" unchanged (so add-ons are unaffected), but customizing balance for each mainline dragon separately.

Even if you want to go that route, I'd say the core fire dragon should still be a reasonable _baseline_ to build up from.

> Frost breath for skeletal dragon.

I kinda think a breath attack on the skeletal dragon doesn't make much sense. Even if it _did_ make sense, why frost instead of fire? How does death and reanimation change fire into frost?

> Flight or Submerge for skeletal dragon (oceans are quite a lot deeper than 10 meters so it surely _can_ submerge).  :p

I suppose there's always the option of compromising by giving it a special submerge ability that only works in deep water tiles that don't have a non-deep-water tile within 2 hexes. (Whether to count land tiles in that would be up in the air.)

2023-08-04 19:10 UTC, Jonathan-Kelly commented
> I can mostly do that ability but I dont feel confident in creating the "each unit in the line of fire has a separate chance to avoid it" so that I would need to get some help with, or someone can just provide the ability(ies).

What do you think about implementing this area of affect ability @CelticMinstrel ?
Also, any progress on #7262 ?

> I kinda think a breath attack on the skeletal dragon doesn't make much sense. Even if it did make sense, why frost instead of fire? How does death and reanimation change fire into frost?

It does not really make physical sense for the skeletal dragon to be able to fly on its skeletal wings either. Or for it to move without muscles. Through some magical process it seems to retrain weaker versions of its living abilities. Retaining some form of "breath" attack would be in line with this. Undead creatures have a high affinity for cold and arcane magics, but never produce fire and tend to be vulnerable to it.

2023-08-05 03:29 UTC, CelticMinstrel commented
> Through some magical process it seems to retain weaker versions of its living abilities. Retaining some form of "breath" attack would be in line with this.

Does it really? Having the ability to move through unspecified magical means doesn't seem like retaining "weaker versions of its living abilities" to me. More like the magic animating it just allows it to move. And I don't think there's any other cases of an skeletal undead having anything akin to a breath attack.

2023-08-05 03:29 UTC, CelticMinstrel commented
> > Through some magical process it seems to retain weaker versions of its living abilities. Retaining some form of "breath" attack would be in line with this.
> 
> Does it really? Having the ability to move through unspecified magical means doesn't seem like retaining "weaker versions of its living abilities" to me. More like the magic animating it just allows it to move. And I don't think there's any other cases of an skeletal undead having anything akin to a breath attack. Skeletons don't have any breath.

2023-08-05 15:55 UTC, Jonathan-Kelly commented
Hmm, I reread the flavour texts for the skeleton units and it sounds like what they retain are just the skills from their former life. Their physical abilities may be more a product of their (re)creation process (as with the ghoul) or the magics vested them by their necromancer. So the skeletal dragon's "flight" and potential "breath" would be due to a necromancer granting those abilities which the creature best remembers how to use well.

2023-08-09 19:46 UTC, Hejnewar commented
Modified Ray special for Fire Dragon:

```
#define WEAPON_SPECIAL_RAY
    [dummy]
        id = ray
        name = _"ray"
        description= _ "This weapon, when used offensively, also deals damage to a unit behind the target."
        active_on = offense
    [/dummy]
#enddef

#define WEAPON_SPECIAL_RAY_EVENTS
    [event]
        name = attacker_hits, attacker_misses
        id = ray_hits
        first_time_only = no
        [filter_attack]
            special_id = ray
        [/filter_attack]
        [store_unit]
            [filter]
                [filter_adjacent]
                    find_in = second_unit
                    adjacent = $second_unit.facing
                [/filter_adjacent]
                [or]
                    [filter_location]
                        [filter_adjacent_location]
                            adjacent = $second_unit.facing
                            [filter_adjacent_location]
                                adjacent = $second_unit.facing
                                [filter]
                                    find_in = second_unit
                                [/filter]
                            [/filter_adjacent_location]
                        [/filter_adjacent_location]
                    [/filter_location]
                [/or]
            [/filter]
            variable = ray_hit_units
        [/store_unit]
        [foreach]
            array=ray_hit_units
            variable=ray_hit_unit
            [do]
                [set_variable]
                    name = ray_hit_roll
                    rand = 1..100
                [/set_variable]
                [store_unit_defense]
                    find_in = ray_hit_unit
                    variable = ray_hit_chance
                [/store_unit_defense]
                [if]
                    [variable]
                        name = ray_hit_roll
                        less_than_equal_to = $ray_hit_chance
                    [/variable]
                    [then]
                        [harm_unit]
                            [filter]
                                find_in = ray_hit_unit
                            [/filter]
                            amount = $weapon.damage
                            damage_type = $weapon.type
                            alignment = $unit.alignment
                            kill = yes
                            experience = yes
                            fire_event = yes
                        [/harm_unit]
                    [/then]
                [/if]
            [/do]
        [/foreach]

        {CLEAR_VARIABLE ray_hit_units,ray_hit_chance,ray_hit_roll}
    [/event]
#enddef
```

Code ft. Jarom. 

No weapon specials, abilities, accuracy or parry values influence chance to hit for units other than primary target, only raw terrain defense matters. 

After thinking accuracy specials shouldnt work on targets beyond the first one from lore perspecitive, magical spells should work like standard ray most of the time but depends on spell.  

Splitting this event into two is also very easy so in case half damage is needed it should be doable.

2023-08-13 19:21 UTC, Hejnewar commented
Fire drag:
Now -10% cold res
21-4 fire breath
Skelly drag:
Now -20% fire and arcane res

2023-08-21 14:56 UTC, Jonathan-Kelly commented
> Code ft. Jarom.

His approach to the separate hit rolls is very clever and elegant. Excellent work.

> No weapon specials, abilities, accuracy or parry values influence chance to hit for units other than primary target, only raw terrain defense matters. After thinking accuracy specials shouldnt work on targets beyond the first one from lore perspecitive,

Yeah, that makes sense. And removing specials really simplifies the implementation. Much less edge case bug potential. The only wrinkle is it will be weird if paired with the `magical` special. But that is minor.

---

After some thinking, I would like to widen the hit zone so as to affect more of the units immediately next to the dragon, since these will be the ones actually attacking it and Zone-of-Controlling it. I also propose having the splash damage work on the dragon's retaliation attacks. Like how it all works for [the blast special](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Winds_of_Fate/utils/abilities.cfg), but using this new per unit terrain factoring hit calculation. Such a special should have many uses for other "boss" units in the future.

Also I want to apply this special to the dragon's tail whip attack or create a similar special which does full damage to the target enemy and any units standing beside both it and the dragon, plus half damage to any other units standing adjacent to just the dragon (in other words, any units close to but behind the dragon get half damage).

Just give me a bit of time so I can throw some code together for all of this.

2023-08-22 07:27 UTC, Hejnewar commented
Honestly, all code I would need is locaion filter and Im pretty sure I have all necressary ones and even if I dont they dont seem hard to make. So no need to code anything. 

That AOE is massive, with the current damage proposed it would kill pretty much anything in 2 to 3 turns all around itself and more. How do you propose players play around that? What is the desired way of fighting this dragon?

2023-08-22 14:51 UTC, Jonathan-Kelly commented
> That AOE is massive, with the current damage proposed it would kill pretty much anything in 2 to 3 turns all around itself and more.

Yes, it would need some power reductions in other areas, like:

fire - 21-4  -> 24-3 or 21-3
tail  - 24-3 -> 24-2 or 24-1

HP - 500 -> 300 or 450
MP - 8 -> 7 (or 6 + skirmisher ability)

Also, for a cost of 12-14 gold per turn, the dragon can be ZoCed by a pair of level 1 recruits positioned on opposite sides of it. Each turn it can eat only one of them, allowing time for another recruit to take its place. Reducing the dragon's MP while adding the skirmisher ability would eliminate this cheap exploit. While the similar exploit of surrounding it completely with 6 level 1 units would be countered by the widened AoE proposed earlier.

> How do you propose players play around that? What is the desired way of fighting this dragon?

Traditionally dragons were slain by elite knights (or in some stories, what could be considered magic wielders). So attacking with small elite bands of level 3-4 warriors (and/or spell casters) should probably be more efficient than using massed fresh recruits.

2023-12-20 12:18 UTC, loonycyborg commented
Will AI be able to use wide aoe properly? Like maximizing number of targets hit etc

2023-12-20 12:40 UTC, ForestDragon-wesnoth commented
> Will AI be able to use wide aoe properly? Like maximizing number of targets hit etc
Currently no. AI does not understand abilities/weapon specials that rely on events.

2024-01-04 23:18 UTC, Tsuki-no-Namida commented
> Fire Dragon [...] (Dont approach without at least 7 ancient liches. It bites.)

It means Fire Dragon will be somehow of a level 20-30 unit in terms of power? (7x4=28)
> Also, Xanthric boss fight in DiD S9 is now kind of heavily one-sided (with mal Keshar being incinerated)

Agree, especially in 1.16 (1.14 was easier for multiple reasons)
> I agree with Dalas's idea

same, I agree with Dalas's idea of keeping originals and add some particular skills, that's exactly what I do in my homemade ongoing campaign;
in my campaign one player asked for using strong dragons, because "dragons are strong", I simply gave him a modded version of each highest level drake, with adding marksman to the most powerful attack among the standard attacks for each one of them, plus Illuminates and two more levels to Flameheart to make Leadership be more effective, and the normal version of Fire Dragon... and that's all... they were just 8 units but resulted an overpowered team in respect of other Wesnoth units, and still balanced.

Also, 
don't forget that for godly units there is already a lot of stuff on add-on server, and that's the place for these things.
> Will AI be able to use wide aoe properly? Like maximizing number of targets hit etc

this here above is the most important question,
> Currently no. AI does not understand abilities/weapon specials that rely on events.

and this here above is the most important answer!
If you transform dragons into godly beings with no brain, Wesnoth won't be a strategical game anymore, but a problem solving game... that's what happened to a turn-based strategy game that I recently left after playing it for more than 10 years, please don't do their same mistake.

Now,
some questions for you to clarify my line as a common player that loves this awesome game:
why a knight is larger and taller than a village and only one knight can enter into a village? Maybe because the knight may represent a team of knights?
And why the ships are all level 1 so any trash unit can sink them easily? Maybe because the trash unit represents a team of units too?
And why archers hit at distance 1, that is, only when enemy is adjacent? Maybe because it represents a distance fight between two teams/armies?
(ofc I know that in some scenarios, especially indoors, tey look like single units... this flexibility is one of the most awesome parts of the game itself)
Imho,
as they are now, these dragons represent great dragon type that can face multiple teams of warriors and can wipe a team (a hex) in one turn, what they may miss the most is an AI that plays them in a challenging way.

As always, thanks to you all for considering my intervention and for your awesome work and commitment on this awesome game!

2024-01-05 06:53 UTC, Hejnewar commented
@loonycyborg
>Currently no. AI does not understand abilities/weapon specials that rely on events.
But MAi does, in fact that has already been done by me in the past, but I don't want to go down that route. Not for the dragon at least, I think I have a better idea. (But really making it understand a bit is very possible even with a bit of wml + wfl so making ai in general be aware of it shouldn't be impossible as well.) So the final answer is yes, I can in fact make ai aware of it and make it maximize the targets or damage, I just don't think I need it really. Not anymore at least. 

@Tsuki-no-Namida 
Hmm i guess i discussed it somewhere else and not here since there doesn't seem to be my the reason why this was postponed here. 

Anyway, I disagree Dragon should be dumb and should be a mountain of stats, it is players job to outsmart it and come out on top. It is fine to lose as long as you learn, that is how you make players feel good, and feel great when they finally beat it. 

Also you really shouldn't be making scale argument, it is different for me and I don't accept your idea of scale. In fact why should I? It is my imagination that tells my that village is smaller than knight because knight is just representation of a unit and village is just representation of part of the map, they exist in different scales. Not to mention different campaigns use different scales. That's very personal thing. 

I on purpose not say what I want to do, it probably is somewhere but it could also be in private chat. In short, bosses don't need great ai to be great enemies for players to fight.

2024-01-05 21:33 UTC, Tsuki-no-Namida commented
> Not to mention different campaigns use different scales. That's very personal thing.

I agree with  you on that, in fact I said in my intervention:
_(ofc I know that in some scenarios, especially indoors, tey look like single units... this flexibility is one of the most awesome parts of the game itself)_
but, in the same way, you cannot exclude that things may be seen by many devs/players as I told:
Fire Dragon is a core/main level 5 unit, then players should be able to beat it with some level 1 units that hit his weaknesses (I even killed one with something like 20 or 30 level 0 goblins), if you want it to be more powerful then better edit it and leave the vanilla version as it is now,
for example, recently I use DiD phantoms exped to full amla'ed 39 hp eidolons in my campaign... so, a spectre remains a spectre, but my ones are godly without wrecking balancement of core units, that's what I would like you devs to follow:
want a godly dragon? Make it be a special unit in a campaign, that's why I agree with Dalas's idea.

> In short, bosses don't need great ai to be great enemies for players to fight.

I absolutely agree with you,
but don't go down this road carelessly till you reach the bottom:
is what slowly transformed the other turn based strategy game I played for many years with loonycyborg into just a problem solving game and made me quit it,
the best comparison of a fight that's already somehow similar in the two games is where a flame boss (and here is exactly the Fire Dragon in 1.16 DiD) stays in unreachable spots, throws stuff to you and automatically beats you with that, or oneturns you if you go for him without making tons of calculations.

Fortunately, in Wesnoth, if you devs will create tons of godly and dumb bosses, I'll should always be able to just cripple your gods with editing savefile ]:) so I don't think I'll quit Wesnoth, but other players may just quit.

Btw, thank you for having answered, I appreciated it since I like to discuss about different views,
and I'm genuinely curious to see how your dragon will be when completed!

2024-01-07 10:15 UTC, ForestDragon-wesnoth commented
>that's what I would like you devs to follow: want a godly dragon? Make it be a special unit in a campaign, that's why I agree with Dalas's idea.
100% agreed. As much as OP boss units can be interesting, they must not be a unit's core stats.

2024-01-07 12:40 UTC, Hejnewar commented
Eh guys now the dragons hp will be 750. It might actually be too little. I really should consider 1000 but that might be slightly too repetetive... 875? Sounds nice. 

I should also add a weapon special that makes the dragon deal more damage after its hp drops below certain treshold. Just to show that it was just toying with you, now it will be serious. Yeah that sounds like great idea. 

And of course its attacks should change at the start of its turn. Yeah that sounds great.

2024-01-07 14:10 UTC, knyghtmare commented
> Eh guys now the dragons hp will be 750. It might actually be too little. I really should consider 1000 but that might be slightly too repetitive 875? Sounds nice.
> 
> I should also add a weapon special that makes the dragon deal more damage after its hp drops below certain treshold. Just to show that it was just toying with you, now it will be serious. Yeah that sounds like great idea.
> 
> And of course its attacks should change at the start of its turn. Yeah that sounds great.
> 
> I mean players should actually feel like they accomplished something, not just killed 100 hp worth of stats.

I mean sure. Go right ahead.

2024-03-05 23:07 UTC, Hejnewar commented
I will close this for now, we already have too many PRs imo I will reopen this / make new one when I fix area of effect specials to work with leadership and stuff.

2024-03-05 23:07 UTC, closed without merging