Fix mp empty side1
wesnoth/wesnoth pull request #8246
Opened 2024-01-15 02:13 UTC by gfgtdf

We refactor a the mp server game turn data a bit to fix #2563 and #3899

2024-01-15 03:29 UTC, stevecotton commented on src/server/wesnothd/game.hpp
> +	simple_wml::node* description_for_writing()
Needs documentation

2024-01-15 03:30 UTC, stevecotton commented on src/server/wesnothd/game.hpp
>  	 * @return True if the current side and-or current turn values have been updated, false otherwise.
Docs out of date

2024-01-15 03:31 UTC, stevecotton commented on src/server/wesnothd/game.hpp
> +	/** Set to true whene ever description_ was changed so that it needs to be sent and update to the clients */
Typo of "whenever"

2024-01-15 03:31 UTC, stevecotton commented on src/server/wesnothd/game.hpp
> +	 * -1 if we currently dont accept [init_side] because the current player didn't end his turn yet.
Typo of "don't"

2024-04-07 00:09 UTC, gfgtdf commented on src/server/wesnothd/game.cpp
> +			return true;
no that's exactly what the `sides_[get_next_side_index()] == user` does, `user` is the user who send this, and  `sides_[get_next_side_index()] ` is the user who is allowed to send this.

2024-08-03 16:26 UTC, Pentarctagon commented
@gfgtdf please address the last remaining review comment, and then I think this can be merged?

2024-08-11 20:31 UTC, soliton- requested changes

2024-08-12 00:50 UTC, gfgtdf commented on src/server/wesnothd/server.cpp
> +	} else {
All of these end with a return, having this outside make its looks like not handled with a return is a possibility.

2024-08-12 00:51 UTC, gfgtdf commented on src/server/wesnothd/game.cpp
> +		return 0;
this is mainly to match the previous behvaior of current_side() which returned 0 in that case and now uses this function.

2024-08-12 08:59 UTC, soliton- commented on src/server/wesnothd/server.cpp
> +	} else {
Of course it's a possibility and it does happen. Are you suggesting that to anyone reading the code the final warning suggests not handling a case is wanted? And if the final warning is in an else case then it suggest you must handle all cases?

2024-08-12 13:22 UTC, gfgtdf commented on src/server/wesnothd/server.cpp
> +	} else {
where does it happen? i didn't find anything

2024-12-15 23:20 UTC, merged