[Units][Skeletal Dragon] Remove ancient comment
wesnoth/wesnoth pull request #8541
Opened 2024-03-12 16:27 UTC by knyghtmare

This comment existed when the unit was still in EI campaign. It's been moved to core ages ago and yet, the comment, now no longer relevant outside of EI still persisted...

Also, why is this _undead_ unit still in `units/monsters/` when `units/undead/` exists?

2024-03-12 16:28 UTC, cooljeanius approved these changes
LGTM, pending CI passes

2024-03-12 16:57 UTC, stevecotton commented
While the current comment isn't relevant outside EI, it probably still needs some comment about why an undead unit has so much arcane resistance. Otherwise within a couple of years I think we'll see a "fix skeletal dragon's broken arcane resistance" PR, so it sounds like a good time to discuss that now.

2024-03-12 17:54 UTC, Dalas121 commented
And if we're on this topic, I know Hejnewar has proposed "boss fight" changes to the fire dragon, which might impact what we want to do for the skeletal dragon.

Seems that removing a comment is pretty complicated 😂

2024-03-14 02:07 UTC, irydacea commented
> Also, why is this _undead_ unit still in `units/monsters/` when `units/undead/` exists?
Because nobody has moved it yet.

2024-03-14 04:40 UTC, knyghtmare commented
> While the current comment isn't relevant outside EI, it probably still needs some comment about why an undead unit has so much arcane resistance. Otherwise within a couple of years I think we'll see a "fix skeletal dragon's broken arcane resistance" PR, so it sounds like a good time to discuss that now.

> And if we're on this topic, I know Hejnewar has proposed "boss fight" changes to the fire dragon, which might impact what we want to do for the skeletal dragon.

I believe it was supposed to be changed
https://github.com/Hejnewar/wesnothrepo/blob/be2a78ceaeeae4f1c29058003284af61d66dc8eb/data/core/units/monsters/Skeletal_Dragon.cfg

arcane would go from 0 to -20%, same for fire resistance.

> Because nobody has moved it yet.

Might as well. change the PR title and adjust the changes.

2024-03-14 16:10 UTC, knyghtmare commented
Most recent commit changes the PR title, adjusts stats to the previously closed PR, and removes the redundant comment. 
I have tagged dalas and Hejnewar for reviewing.

2024-03-14 22:19 UTC, cooljeanius requested changes
This is going too far now; please just put it back to the comment replacement

2024-03-14 22:23 UTC, ProditorMagnus commented
It looks overpriced.

2024-03-15 00:05 UTC, Dalas121 commented
Changes look plausible to me. A few thoughts:

The undeadfly movetype already includes -20 arcane/fire resistance, so no need to specify those lines in the .cfg file.

I agree that price seems a little bit on the high end compared to the ancient lich. But let's be real, who's out here recruiting level 4 units? Price is pretty irrelevant at that level.

The only mainline campaigns that use the Skeletal Dragon are DiD and EI.  I can handle updating EI if this change goes through; and I'm not sure DiD even needs changes since it's a player-controlled unit that's only usable in the final (infinite) scenario.

Design-wise, I feel that it's better to design bosses around their minions, rather than give them massive solo power (though this really isn't that much solo power anyway).

Regardless, for a unit as unique as the skeletal dragon I expect campaign authors will want to customize each one to their own liking anyway, and the provided stats seem like a respectable baseline.

2024-03-15 00:10 UTC, Dalas121 approved these changes

2024-03-15 00:10 UTC, ProditorMagnus commented
Price can act as information for ai how much to value killing it, and for scenarios how much to reward player for killing it.

2024-03-18 23:33 UTC, Hejnewar commented
Huh 4 days ago and I just noticed, pls ping on discord. It should be 288. It might seem like a lot but this dragon can with no luck kill 5 troll wariors maybe even 6 (if it doesnt level) at once. Yeah it is not a bad (archmages say hello or similar) but also not a good matchup. It is worth remembering that unit stats in wesnoth scale close to linearily only until some point, after which they start to become multiplicative and thus cost but also combat performance start to subvert expectations which can be very apparent in units like dragons cuz they have massive flat stats. 

Since dragon is weak to strategy its performance in hands of ai might not be the same as in hands of a player and thats what the prices are based on, still it is good to realise that the skele drag will kill lots of lvl 3s without strategy from a player.

2024-03-19 06:31 UTC, knyghtmare commented
>  It should be 288. 

Done.

2024-03-19 21:53 UTC, Hejnewar approved these changes

2024-04-01 19:48 UTC, Pentarctagon commented
Hejnewar approved, so I assume this can go in?

2024-04-01 21:20 UTC, cooljeanius commented
> Hejnewar approved, so I assume this can go in?

I guess for 1.19, but for 1.18 it should be limited to just the comment update, IMO.

2024-04-02 04:54 UTC, knyghtmare commented
> Hejnewar approved, so I assume this can go in?

It can go in, but for 1.19, I would suggest rebalancing the scenarios in which this unit will appear in. Such as the last scenario of Descent to Darkness and the scenario in Eastern Invasion in which it appears.

Also, I was postponing this PR merger because I was waiting for the Fire Dragon to gets stat adjustment.

2024-05-09 16:12 UTC, Earth-Cake commented
I feel like a unit this strong and costly should not be level 4, but level 5.

2024-05-11 10:48 UTC, knyghtmare commented
> I feel like a unit this strong and costly should not be level 4, but level 5.

If hejne is okay with making it a level 5, I can do that, but otherwise, no. What's a level 4 should stay a level 4.

2024-08-03 16:13 UTC, merged

2024-08-03 16:13 UTC, Pentarctagon commented
> The only mainline campaigns that use the Skeletal Dragon are DiD and EI. I can handle updating EI if this change goes through; and I'm not sure DiD even needs changes since it's a player-controlled unit that's only usable in the final (infinite) scenario.

@Dalas121 FYI