Allow [experimental_ability(_active)]apply_to= to check damage types in abilities [resistance]
wesnoth/wesnoth pull request #8926
Opened 2024-05-26 15:58 UTC by newfrenchy83

Until now apply_to= could only be used to check if the ability used as a weapon applied to 'self|opponent|attacker|defender' but abilities [resistance] which use apply_to= to determine the types of damage concerned remained excluded.

if all the elements of the list to be checked are present in the ability, then it will match, for example if we look for apply_to=arcane, fire in an ability [resistance]apply_to=arcane, fire, cold, it will match even if its list is longer than the one used for the backward check if [resistance]apply_to=arcane, impact, cold, this will not match because 'fire' will be missing.

2024-05-30 16:35 UTC, newfrenchy83 commented
@stevecotton @soliton- could you review th PR, please? This is the last before to move code in abilitie.cpp

2024-06-01 21:01 UTC, stevecotton commented
Please add a test to show what the new functionality is - I'm not understanding the aim from the PR description.

2024-06-01 21:47 UTC, newfrenchy83 commented
> Please add a test to show what the new functionality is - I'm not understanding the aim from the PR description.

test added

2024-06-05 18:13 UTC, soliton- commented on src/utils/config_filters.cpp
> +	const std::vector<std::string> filter_attribute = utils::split(filter[attribute]);
Why is this not a set as well?

2024-06-05 18:41 UTC, newfrenchy83 commented on src/utils/config_filters.cpp
> +		if (cfg_attribute.count(fil_at) == 0){
it's not if (!cfg_attribute.contains(fil_at)){ instead?

2024-06-05 21:28 UTC, newfrenchy83 commented on src/utils/config_filters.cpp
> +	const std::vector<std::string> filter_attribute = utils::split(filter[attribute]);
fixed

2024-06-05 21:29 UTC, newfrenchy83 commented on src/utils/config_filters.cpp
> +		if (cfg_attribute.count(fil_at) == 0){
compilation fail with this.

2024-06-05 21:30 UTC, newfrenchy83 commented on src/utils/config_filters.cpp
> +bool utils::config_filters::matches_if_each_string_element_matches(const config& filter, const config& cfg, const std::string& attribute)
renamed to set_includes_if_present

2024-06-07 11:16 UTC, soliton- commented on src/utils/config_filters.cpp
> +		if (cfg_attribute.count(fil_at) == 0){
Oh my bad that is C++20.

2024-06-07 12:04 UTC, soliton- requested changes
Commit message should be:
> Modify 'apply_to' in an ability filter to do an inclusion check for resistance abilities
> 
> Instead of needing to contain the exact string from the ability, 'apply_to' in the filter is now taken as a comma-separated list, where all elements need to be present in the ability.
For example if we filter for apply_to=fire,arcane given an ability [resistance]apply_to=arcane, fire, cold, it will match.
For an ability [resistance]apply_to=arcane, impact, cold, this will not match because 'fire' is missing.

2024-06-07 13:13 UTC, newfrenchy83 commented on changelog_entries/modify_apply_to_in_filter_ability.md
> +   * modify 'apply_to' in [experimental_filter_ability(_active)] or [overwrite][experimental_filter_specials] for check list of damage type in [resistance] abilities.
done

2024-06-07 13:13 UTC, newfrenchy83 commented
> Commit message should be:
> 
> > Modify 'apply_to' in an ability filter to do an inclusion check for resistance abilities
> > Instead of needing to contain the exact string from the ability, 'apply_to' in the filter is now taken as a comma-separated list, where all elements need to be present in the ability.
> > For example if we filter for apply_to=fire,arcane given an ability [resistance]apply_to=arcane, fire, cold, it will match.
> > For an ability [resistance]apply_to=arcane, impact, cold, this will not match because 'fire' is missing.

commit message changed

2024-06-07 13:13 UTC, newfrenchy83 commented on src/utils/config_filters.hpp
> + * for the function to return true.
docxygen chaged

2024-06-07 16:08 UTC, merged