Proposed New Wyvern Rider Description
wesnoth/wesnoth pull request #9020
Opened 2024-06-22 20:02 UTC by Gothyoba

I know I alreayd made a PR for this around a year sgo, but the writing was not very good and I ultimately abandoned the idea. However, I have decided to this to propose a new and hopefully much better description. I doubt it will get added, though I hope this unit can eventually get a description. It feels like a work in progress like this, and a unit like this could have an interesting description.

2024-07-01 17:37 UTC, Wedge009 commented
I'm guessing English is not your native language. There's a bit of inconsistency with 'travellers' using en_GB spelling while 'skillfully' is en_US spelling. Wesnoth uses en_US by default so should probably change 'travellers' to 'travelers'.

It's not a bad description (and I'm a bit surprised the current description is blank), but it doesn't quite flow smoothly to me as a native Anglophone. But then, I'm also not a writer. Probably best for this to be reviewed by those in charge of the prose text.

2024-07-01 20:01 UTC, CelticMinstrel commented on data/core/units/dunefolk/Wyvern_Rider.cfg
> +    description= _ "Wyverns are fierce and angry beasts, especially when provoked. Most travellers would run or fight in their mighty presence. Yet a few are able to tame these wild creatures. These
Preliminary suggested changes:

* Merge sentences 2 and 3 into a single sentence, with a comma
* Add an article for "creatures"
* Make "home" plural
* Don't capitalize the race name

The result:
```suggestion
    description= _ "Wyverns are fierce and angry beasts, especially when provoked. Most travellers would run or fight in their mighty presence, yet a few are able to tame these wild creatures. These dunefolk riders spend years, even decades of their lives bonding with the creatures. They skillfully dedicate their lives to art of flying the wyvern. While these masters do not usually use this art in warfare, they have been known to become threatening warriors when defending their homes."
```

I think it still has some problems even with these changes. In particular, the sentence with "skillfully" feels awfully abrupt.

2024-07-01 20:56 UTC, CelticMinstrel commented
Still a bit unsatisfying, mainly the "greatly linked" and the following sentence…

2024-07-01 21:28 UTC, Gothyoba commented
I changed some parts of the description. I think it sounds better now, but I’m not quite happy with it, especially at the end. If this does not get added, I think the Wild Wyvern description should probably be used here as a placeholder. As far as I’m aware, this is the only completely blank description.

2024-07-02 04:24 UTC, CelticMinstrel commented
Okay, at this point I don't have anything else to add, so I say we should wait and see what @nemaara things.

2024-07-08 18:45 UTC, knyghtmare requested changes
Maybe add these changes:

```txt
Although generally peaceful, when provoked wyverns can easily become fierce and angry beasts. When truly enraged they can even tear apart experienced warriors with relative ease. Most travelers would run or fight in their mighty presence, yet a few are able to tame these wild creatures. These Dunefolk riders spend years, even decades of their lives bonding with them, slowly building up their trust until they have gained true mastery over the skies. The most experienced of these Wyvern riders have ascended to be the greatest and most revered travelers of the land. While they do not usually use their knowledge for warfare, they can be threatening warriors when defending their homes.
```

2024-07-08 19:44 UTC, Dalas121 commented
Is there any established lore on Wyvern Riders and how (if?) they fit into canon? Any high-profile UMC that feature them? Or are we working from a blank slate.

2024-07-08 20:51 UTC, Gothyoba commented
@knyghtmare This looks good to me. I’ve added the changes.
@Dalas121 I don’t know of any UMC that use the Wyvern Rider in any significant way. I personally haven’t found any but I’m probably wrong given the amount of dunefolk campaigns.

2024-07-09 00:54 UTC, CelticMinstrel commented
Didn't they originally come from a user-made campaign? I think it might've been Oath of Allegiance. It does have a wyvern rider line, at least, not sure if it's the _original_ source though.

2024-07-09 01:57 UTC, Dalas121 approved these changes

2024-07-09 12:41 UTC, CelticMinstrel commented
The full sentence:

> Although generally peaceful, when provoked wyverns can easily become fierce and angry beasts.

Putting a semicolon there doesn't make any sense. The proposed comma would be acceptable, but I think it flows fine without it. It would flow even better if "when provoked" moved to the end of the sentence though… but maybe there was a reason for fronting it?

2024-07-09 17:26 UTC, Wedge009 commented
> Although generally peaceful, when provoked wyverns can easily become fierce and angry beasts.

I think the punctuation is okay here.

2024-07-09 19:20 UTC, knyghtmare approved these changes

2024-07-10 06:55 UTC, merged