LoW: some fixes for S10, S22
wesnoth/wesnoth pull request #9128
Opened 2024-07-24 15:31 UTC by amakriLexa04

Well, I was bored and decided to fix a few small bugs in LoW. I can't say that I did my best, but I got the job done.

List of fixed issues:
[LoW S9 and S10: Scenario designs are too similar #7137 ](https://github.com/wesnoth/wesnoth/issues/7137)
[LoW: Clarify player's veterans joining Landar #8359 ](https://github.com/wesnoth/wesnoth/issues/8359) 
[LoW S22: Enemy camp starts too close to friendly camp #8360 ](https://github.com/wesnoth/wesnoth/issues/8360)

2024-07-24 15:48 UTC, amakriLexa04 commented
I'm sorry about that. I'll name the next commits properly

2024-07-24 19:58 UTC, soliton- commented
No worries. There is just a single commit so the commit message can also be adjusted when doing a squash merge.

2024-08-04 19:50 UTC, Dalas121 requested changes
Thanks for working on this! Couple grammar things:

Can you change: _"Some of Kalenz’s veterans joined the host of the Northern Elves under Uradredia, but most have chosen to be traitors and join Landar. Very soon, enemy army appeared..."_
To: _"Though some of Kalenz's veterans had joined Landar in revolt, others instead joined the northern host under Uradredia. Very soon, the Landar’s army appeared..."_

And can you change: _"wanting to stow their weapons and who now stands with Uradredia"_
To: _"to stand with Uradredia"_

2024-08-04 21:23 UTC, amakriLexa04 commented
Done

Also, I will be happy to help with anything else related to WML

2024-08-04 21:35 UTC, Dalas121 commented
Thanks!

Ack, I made a typo.  _"the Landar’s"_ should just be _"Landar’s"_.  Sorry about that!

2024-08-04 21:36 UTC, Dalas121 approved these changes

2024-08-04 21:49 UTC, amakriLexa04 commented
Fixed this typo

2024-09-14 11:35 UTC, stevecotton commented
@Dalas121 is there anything else to do here?

Reminder to squash-merge the PR.

2024-09-14 16:47 UTC, soliton- commented on data/campaigns/Legend_of_Wesmere/scenarios/chapter5/22_Northern_Battle.cfg
> +            story= _ "Though some of Kalenz's veterans had joined Landar in revolt, others instead joined the northern host under Uradredia. Very soon, Landar’s army appeared..."
This replaces the proper right quotation mark with an apostrophe.

2024-09-14 20:00 UTC, merged

2024-09-14 20:00 UTC, Dalas121 commented
Squashed. Let me know if the commit message was OK, or if I should have changed it.

2024-09-15 11:10 UTC, soliton- commented
The commit message github proposes is never good. No point in writing 3 times the same thing for example.

Would have been nice if the comment I made would have been acted on before merging.

2024-09-15 14:18 UTC, Dalas121 commented
Oh, I misunderstood your comment. Sorry about that; I'll fix that apostrophe.

2024-09-15 14:19 UTC, Dalas121 commented
Ah, nevermind, looks like you fixed it already.