[SotBE] replace mature phrase in S14
wesnoth/wesnoth pull request #9141
Opened 2024-07-28 14:24 UTC by knyghtmare

The phrase was swapped out in the campaign descriptions but stayed in the dialogue here. 
Is this even allowed in kid-friendly games?

2024-07-28 18:59 UTC, Dalas121 commented
I don't have an issue with the phrase in question, but I also don't have an issue with removing it.  Note that this would need to be removed from SotBE's S15 as well, plus several in LoW.

https://github.com/search?q=repo%3Awesnoth%2Fwesnoth+tree-shagger+path%3A*.cfg&type=code

2024-07-28 19:00 UTC, Dalas121 requested changes
I don't have an issue with the phrase in question, but I also don't have an issue with removing it. Note that this would need to be removed from SotBE's S15 as well, plus several in LoW.

https://github.com/search?q=repo%3Awesnoth%2Fwesnoth+tree-shagger+path%3A*.cfg&type=code

2024-07-29 03:32 UTC, doofus-01 commented
The original line had aggression and insult, the proposed replacement just seems weird, maybe a human prince would say something like that.  "Tree-huggers" might be closer to the original intent?

2024-07-29 13:43 UTC, CelticMinstrel commented
I don't think the removed phrase is all that bad (from my perspective it seems like kinda a more niche swear word), but I think I also agree with doofus that the replacement doesn't fill the same role – "wose-born" sounds like something that the orcs might use if they were trying to be _polite_. I guess "tree-huggers" does work better. I'm not sure whether it truly comes across as an insult, but I guess in context it might be fine.

2024-07-31 10:41 UTC, stevecotton commented
"Tree-huggers" is a real-world insulting name for environmentalists, while "tree-shaggers" appears to be almost unused on the web. Even on the Urban Dictionary, there's only one entry for "tree shagger", and it appears to be performance in a tree, or maybe on drugs, rather than partnering with the tree itself.

2024-08-01 09:58 UTC, knyghtmare commented
> while "tree-shaggers" appears to be almost unused on the web. Even on the Urban Dictionary, there's only one entry for "tree shagger", and it appears to be performance in a tree, or maybe on drugs, rather than partnering with the tree itself.

I believe the original meaning is "breeding a tree" (sorry, got no filter). 
Anyways, what's the replacement phrase you lot voting on?
- Tree-hugger
- wose-born
- tree-shagger (no change)

2024-08-02 12:34 UTC, Zireael07 commented
To shag is an extremely obscure equivalent of to f**k or to make love. I can find no indication of it being mature or not.

IMHO (English major) not an issue, unless someone can find a source that clearly says it's mature (and even then I think very very few people would realize it's mature, it's so obscure)

2024-08-02 17:39 UTC, CelticMinstrel commented
For what it's worth, the word is also used in the title of a Austin Powers film. That's about 25 years ago, but it shows at least some people in the film industry at the time also didn't think it was censor-worthy.

2024-08-02 18:28 UTC, knyghtmare commented
Sigh. You all made your point. I give up.

2024-08-02 18:28 UTC, closed without merging

2024-08-02 19:18 UTC, cooljeanius commented
> To shag is an extremely obscure equivalent of to f**k or to make love. I can find no indication of it being mature or not.
> 
> IMHO (English major) not an issue, unless someone can find a source that clearly says it's mature (and even then I think very very few people would realize it's mature, it's so obscure)

I wouldn't say it's "extremely obscure", it's just a Britishism

2025-03-30 16:52 UTC, babaissarkar commented
https://en.wiktionary.org/wiki/shag

Makes it pretty obvious it's a mature word, along with sources. Why keep something that has a remote chance of being offending? This is no proprietary game either, we can change things pretty fast. Remember not everyone has the same attitude toward the meaning of the word in question.

2025-03-30 16:59 UTC, babaissarkar commented
This should hopefully be most of the instances:
```
Son_Of_The_Black_Eye/scenarios/15_Civil_War.cfg
188:            story= _ "Kapou’e vowed that this would not happen. Events had the smell of a treacherous plot aimed at destroying the unity of the orcs. Furthermore, if the tree-shagger was to be trusted, then Shan Taum the Smug was behind it all. What an orc expected to gain from destroying his own race was beyond Kapou’e, but he decided to march to Bitok personally and confront the traitor. Bitok being on the far side of orcish territory, this would also give him a good chance to clobber the orcs into working together again — the old-fashioned way."

Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg
722:                    message= _ "The human-worms and tree-shaggers have gone too far! BLOOD AND STEEL! I want every human and elf in this area slaughtered! Show no mercy, give no quarter!"
734:                    message= _ "<i>What</i>?! The human-worms and tree-shaggers have gone too far! BLOOD AND STEEL! I want every human and elf in this area slaughtered! Show no mercy, give no quarter!"

Legend_of_Wesmere/scenarios/chapter1/01_The_Uprooting.cfg
340:            message= _ "Surrender or die, tree-shaggers!"
514:            message= _ "Curse you, tree-shaggers! We will feed your young to our wolves!"

Legend_of_Wesmere/scenarios/chapter1/03_Kalian_under_Attack.cfg
246:            message= _ "Chief, the cursed tree-shaggers are defeating us!"
655:            message= _ "Cursed tree-shaggers and their filthy bows! We shall await the main army."

Legend_of_Wesmere/scenarios/chapter2/04_The_Elvish_Treasury.cfg
409:            message= _ "I am ashamed to die at the hands of tree-shaggers!"

Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg
643:            message= _ "Be grateful, tree-shagger, for I have spared you the pain of seeing your precious citadel burned and razed."
```