wesnothd: avoid a race condition when logging on
wesnoth/wesnoth pull request #9183
Opened 2024-08-07 17:23 UTC by loonycyborg

Ensure that there is no coroutine yield between confirmation of login
and update of player_connections_. Otherwise another login under same
name could succeed if it happened before handle_player() which resulted
in an assert later.

2024-08-08 09:37 UTC, soliton- requested changes
`is_login_allowed` may still yield after the check and return true.

Probably easiest to move the autokick handling out of that function.

2024-08-08 09:37 UTC, soliton- commented on src/server/wesnothd/server.cpp
> +	assert(inserted);
Would be nice to add a comment that explains a bit what assumptions are being violated if this assert triggers. And by comment I mean `assert(inserted && "...")`.

2024-08-08 18:30 UTC, loonycyborg commented
Although `is_login_allowed` does yield, the only yield point is in a loop that doesn't exit unless name isn't taken. So if it returns true nothing else would have a chance to add that username. However, if something else manages to re-add that username immediately after kick during that yield then the loop will not terminate.

2024-08-08 18:39 UTC, loonycyborg commented
I'm a little fuzzy on how exactly boost::asio::post(yield) works but if it runs only zero or one handler then there's no chance of something else re-adding the username.

2024-08-09 09:46 UTC, soliton- commented
Ok, it's true that the loop checks the name after yield. IMO that's not particularly easy to understand and easy to trip up a future reader but it's technically correct.

2024-08-09 09:50 UTC, merged