Tweak Elvish Marshal Stats
wesnoth/wesnoth pull request #9512
Opened 2024-10-26 07:54 UTC by MechanicalDragon963

Since the 1.18 elf enhancements were deemed excessive and received a rollback of one sort or another, there is no reason to leave Marshal in an over-enhanced form. 

However, a full rollback to 1.16 was found to be controversial. I propose a different solution: 

```
HP: 68 -> 62 
MP: 5 -> 6 
```

This way, Marshal will lose some combat power, but will become stronger as a leader. This will emphasize his differences from the Champion and equalize both options in terms of strength.

2024-10-26 13:16 UTC, ForestDragon-wesnoth commented
Looks reasonable. Better than keeping Marshal as a tank

2024-10-26 13:41 UTC, Jonathan-Kelly commented
It is quite sensible how this change makes the elvish leader just as quick on his feet as his plate armor clad human equivalent, the General.

2024-10-27 08:01 UTC, knyghtmare requested changes
- Cost should not stay at 67, could be 64 (decreased for the HP debuff, but not much due to the +1 MP  buff)

2024-10-27 08:16 UTC, Roge-Tebnelok commented
> It is quite sensible how this change makes the elvish leader just as quick on his feet as his plate armor clad human equivalent, the General.

Shouldn't Elvish Captain's mp be buffed as well? Though I would rather slow General and other leaders down instead of increasing Captain's/Marshal's mp, Hero is still more preferable than Captain, due to the latter's worse stats, leadership doesn't really help him, at least in SP.

2024-10-27 09:29 UTC, ForestDragon-wesnoth commented
> Shouldn't Elvish Captain's mp be buffed as well?

Captain is already pretty much to hero in effectiveness, and one of the benefits of a MP buff is that Marshall is not useless in lategame when players have mostly lvl3 units.

2024-10-27 10:04 UTC, Roge-Tebnelok commented
Captain is weaker than Hero in all terms, from hp and damage to price and experience, if we're comparing their stats in 1.18, in 1.16 their xp is equal, but leadership is the only real advantage Captain has over Hero, and only before most recruits hit level 2 or die, and this happens fairly quickly in SP with precise xp feeding and even faster in MP with reduced xp, so this advatage is doesn't last for long, unless player wants to get more vets than thay can possibly use, and Hero is usually a better option. Lieutenant doesn't have the same problem because he is in the separate line, same goes for Orcish Ruler and Death Squire, Drake Flare has significant melee advantage over Fire Drake, though I would increase Flare's/Flameheart's mp too, for the same reasons why Captain/Marshal need a speed buff.

2024-10-27 10:36 UTC, MechanicalDragon963 commented
The elvish captain is fine as is. The purpose of this PR is to resolve the contradiction with Marshal, not to create a new, even more contradictory problem because of the strong tie to the MP. That's why I don't want to change the captain. 

@knyghtmare  As for the price, I believe a few gold won't create any difference for a level 3 fighter. I believe that +1 move for a leader is equivalent to -6 HP, so I decided to keep the price the same.

2024-10-27 11:44 UTC, Dalas121 approved these changes

2024-10-27 13:42 UTC, knyghtmare approved these changes

2024-10-27 17:41 UTC, Dalas121 requested changes
One point of consideration - with this change, the Marshal is almost entirely better than the General. Better melee, better range, same moves, better movetype, and more hp (which is roughly equivalent to the General's 10% resistances).

I have no issue with the Marshal being equal to or better than the General *overall*, but I do feel the General should at least be better at *something* (aside from being able to level into the Grand Marshal).

That could mean nerfing the 6mp Marshal, or that could mean leaving it at 5mp and making a different change instead.

I'm also open to making a separate PR to minorly buff the General instead.

2024-10-27 18:49 UTC, Jonathan-Kelly commented
> I'm also open to making a separate PR to minorly buff the General instead.

He always suffered from an incredible lack of hit points. Even less than the Arch Mage or the peer level fencer (Master at Arms).

2024-10-28 02:11 UTC, Dalas121 commented
> I do feel the General should at least be better at _something_

Then again, the Orcish Sovereign is also pretty much strictly better than the General, so maybe we should just accept the General being weaker - compensated for by the unique Grand Marshal.

2024-10-28 02:20 UTC, MechanicalDragon963 commented
@Dalas121  

In this case, I can suggest 3 options: 

- Nerf Marshal HP to 60 (6 MP);
- Exclude MP buff from Marshal, leave 62 HP (full revert to 1.16 stats);
- Exclude MP buff from Marshal, nerf HP to 64 instead of 62; 

Which one do you prefer?

2024-10-28 02:52 UTC, Dalas121 commented
I would prefer option #1, to nerf Marshal HP to 60 (6 MP).

While I think the General would still be noticeably weaker, I no longer think this comparison is as important as I was worried about earlier.

But, having 6 MP / 60 HP will make for a meaningful difference compared to the Champion. Hopefully 6 MP this will also help Marshals feel less redundant once the player has mostly level-3 units.

2024-10-28 06:33 UTC, ForestDragon-wesnoth commented
I prefer option 2 or option 3

2024-10-28 08:55 UTC, Tezereth commented
I'd rather not have the Marshal HP get lowered to 60 (or even lower) if possible, that might be too low, especially in contrast to the Champion.
Though when it comes to having 6mp, it is admittedly an interesting prospect, synergize well with leadership while not buffing marshall to be better in combat than champion. Movement is quite strong though, so it would need some testing.
Ultimately, I'm not strictly against it.

2024-10-28 17:56 UTC, MechanicalDragon963 commented
> I would prefer option #1, to nerf Marshal HP to 60 (6 MP).

Okay, I made a commit impementing this option.

2024-10-28 21:09 UTC, Dalas121 commented
> I prefer option 2 or option 3 over making marshal hp even lower than 1.16, with 62hp + 6mp at least one stat was with a 1.16 value, but now it's both changed.

> I'd rather not have the Marshal HP get lowered to 60 (or even lower) if possible, that might be too low, especially in contrast to the Champion.

As far as balance goes, I think any of the proposals (including 1.18's 68hp) are likely to be fine. The average campaign won't be imbalanced by +/- a few HP on a level 3.

If our goal is simply to revert to 1.16, I already expressed my approval in the other PR - but Hejnewar feels that such a change would be too significant of a nerf (I disagree, but w/e).

However, I do believe that the Marshal has a design issues independent of its balance which can possibly be addressed here. Unlike similar units such as the General or Sovereign, the Marshal competes directly with the Champion. Since the Marshal's only superior feature is leadership, in SP campaigns you usually promote a couple of them early-game, then stop recalling them later-on once your recall list fills up.

In comparison, look at the drake Flameheart vs vs Inferno Drake. The Flameheart's superior melee gives it a unique advantage over the Inferno Drake, even without accounting for leadership. Thus, Flamehearts (in my experience) feel less wasteful even when there's fewer units to lead.

Ideally, I feel that the Marshal/Champion would have a similar relationship as the Flameheart/Inferno Drake. I'm not sure if 6mp alone necessarily accomplishes that, but I do think it comes closer than the current design.

2024-10-29 15:37 UTC, Dalas121 approved these changes

2024-10-30 14:37 UTC, MrTitainin commented
I personally think that we should nerf its melee to 9-4 rather than HP, but current proposal is ok.

2024-11-02 09:39 UTC, MechanicalDragon963 commented
As for damage reduction, in my opinion a good solution would be to do it like this: 

Marshal: 9-4, 62 РP, 5 MP 
Champion: 9-5 (no accuracy), 72 HP, 5 MP.

This way, the Marshal's combat strength would be obviously lower than the Champion's.  

I'm not sure that reducing damage in exchange for 10 marksmanship was a good decision in the context of the unit line as a whole. Right now, Marshal and Champion have the same total sword damage, which combined with the increased HP caused the problem.  

But I am not insisting on this solution and just voicing it to hear what others think.

2024-11-02 12:11 UTC, ForestDragon-wesnoth commented
I agree with the idea of reverting champion to 9x5

As for marshal, the old 1.16 value of 10-4, 62hp and 5mp is honestly fine in my opinion, 40 damage is still less than 45 total

2024-11-07 02:50 UTC, Dalas121 commented
Mech has requested that I merge this. As this is primarily a campaign unit, I've done so.

2024-11-07 02:50 UTC, merged