Revert of the Arcane Resistance Rework
wesnoth/wesnoth pull request #9585
Opened 2024-11-17 09:29 UTC by ForestDragon-wesnoth

This PR reverts the controversial 1.18 arcane rework back to 1.16-like (and existing since version 1.4 for 15 years) values of arcane resistances, and several additional damage changes listed at the bottom of the description.

**Reasons for the revert:**

1. **How the change was designed/handled during the 1.17 dev builds:**

While the arcane rework was still being designed/PR-ed, it got an extremely low amount of comments (4 on the forum thread (half of which are from the creator of the rework), and 13 comments on the github PR) for such a colossal change, but after 1.18 release it got quite significant backlash.

https://forums.wesnoth.org/viewtopic.php?t=57075

https://github.com/wesnoth/wesnoth/pull/7801

The reasoning provided in the original forum thread also seems rather vague and far insufficient to justify such a major change being made to the game in the first place - "changing all the resistances to better fit the growing needs of PvE and PvPvE, as well as potentially help with introduction of arcane based units on lower levels.".

If by PvPvE the MP Lead means things like Afterlife, that popular custom gamemode already has its own custom era to better fits the specific needs of such gameplay.

"potentially help with introduction of arcane based units on lower levels" becomes irrelevant if arcane becomes basically "fire that can also harm drakes" - at that point you just get an orc archer equivalent (pierce + fire, with drakes having -10% to pierce/arcane) with extra steps. There is no point of introducing arcane if the damage type itself no longer introduces anything interesting.

2. **Loss of the original design/uniquness/theme:**

What was once arguably the most interesting and unique damage type in the whole game, now feels more like a slightly different variant of fire damage that drakes aren't resistant to, but is almost indistinguishable from fire when fighting undead - skeletons/ghouls have identical resistances to those damage types, and for the majority of units the resistance to it now ranges between -20% and 10%. The only exception among the undead are walking corpses, which were just lucky enough to not get reworked before the 1.18 feature freeze.

In return, while being weaker against undead/magical units it previously countered, it instead is now slightly better against humans and many other non-magical living beings that had 20% arcane resistance before. 

As a result, units that relied on arcane damage went from specialists into generalists (especially if the base damage was also increased. for example, the rather infamous but now-partially-reverted 16x5 sylph buff, or the much more moderate example of paladin being buffed from 8x5 to 9x5 which combined with the human arcane resistance nerf makes him noticeably better against other humans)

3. **Impact on UMC content:**

The arcane resistances in question were consistent from version 1.4 (released in 2008) until the 1.17 dev build (2023), spanning 15 years of Wesnoth's development. The 1.18 rework fundamentally altered these resistances at the movetype level, affecting not only mainline units but also lots of custom human/undead units in UMC.

This is particularly significant because modders have relied on the pre-1.18 arcane resistance values for over a decade. Custom factions, campaigns, and scenarios were built with the expectation that arcane resistances were stable. Altering them so drastically disrupts balance across many add-ons unless developers explicitly override the new defaults.

There have also been multiple modders intentionally switching from mainline movetypes to custom ones to not have to deal with the controversial 1.18 changes (including Era of Magic, the most popular custom era getting such a change https://github.com/inferno8/wesnoth-Era_of_Magic/commit/2b7a547409814c95414e7c5e4c734bada62a4aa9#diff-803eb6e240fed7ba525943e203392d9f370af6ac39c0f753d20ba166199b11bd )

For mods still relying on default movetypes, this PR would simply revert resistances to their pre-1.18 values. Since most add-ons on the server are ports of content created before 1.18, they are generally already balanced for 1.16 or have earlier versions available as reference if adjustments were made for 1.18.

Previously the design approach of mainline balance was smaller and rarer changes, which resulted in mainline being a very stable foundation to build on top of. 1.18 broke that trust, and now mainline is no better than using a custom era as a dependency.

Thus, reverting arcane resistances to their 1.16 values would be far less disruptive for UMC than the 1.18 rework itself.

Alongside resistance reverts, the PR also includes damage nerfs to certain units with arcane attacks who got buffed in 1.18 around the arcane rework:

enchantress: 11x4 > 9x4 (1.16 value)
sylph: 13x5 > 10x5 (1.16 value)
paladin: 9x5 > 8x5 (1.16 value)
necromancer shadow wave: 16x2 > 13x2 (not 1.16 value. necromancer's cold attack got buffed from 17x2 to 19x2 in 1.18. since the necromancer changes are outside the scope of this PR, I set it to 13x2 to keep a similar ratio between cold/arcane damage as on lvl1-2)

2024-11-17 09:54 UTC, MechanicalDragon963 commented
Thank you for such detailed describe of arcane rework issues. I agree that this change was not reasoned and merged into mainline too fast. It brings more controversy than improvements, so I fully support revert of it.

2024-11-17 10:05 UTC, Refumee commented
I fully support this revert. The arcane rework really confused me as an UMC author. I believe I am not the only one.

2024-11-17 11:32 UTC, dashomew commented
I totally agree with point 2.

I am all for a revert to happen.

Anyways... if i had to deal with it here are my suggestion:

Keep 1.18 - Ogres: [1.16] 20%, [1.18] 10%.  

Revert 1.16 - Humans: [1.16] 20%, [1.18] 10%.

Keep 1.16 or -20% Compromise - Drakes: [1.16] -30%, [1.18] -10%.

Keep 1.16 or Skeletons: [1.

2024-11-17 11:45 UTC, kameramen0106 commented
I salute you for this compelling writing and your efforts. I fully support this revert.

The changes for 1.18 were, to put it bluntly, detrimental to the development of the game. I know some of anyone will disagree with this opinion of mine. But those changes did not just cause major negative effects for balance and UMC. They were controversial and left huge conflicts and wounds.

It may be somewhat emotional, but I am convinced that these are unhealthy conditions that need to be corrected as soon as possible. I support this PR anyway, for all the above reasons and more.

2024-11-17 12:11 UTC, ForestDragon-wesnoth commented
Due to the PR description already being long, I decided to split this section into a separate comment for now, as a continuation of Reasons for the revert:

4. **The Damage Itself:**

To address potential concerns about -50% being too much damage, I would like to compare the damage that arcane-dealing units can do to units with the old arcane weaknesses versus other damage types (assuming neutral ToD):


examples of level 3 arcane units attacking units with the old -50% weakness to arcane:


Mage of Light: 18x3 against skeletons - 54 total (meanwhile with the 1.18 resistances it is 14x3 - 42 total)

Paladin: 12x5 against skeletons - 60 total (meanwhile with the 1.18 resistances and 1.18's +1 damage buff it is 11x5 - 55 total)

Lich arcane: 13x3 against skeletons - 39 total (meanwhile with the 1.18 resistances it is 11x3 - 33 total)

1.16 Necromancer arcane: 18x2 against skeletons - 36 total (1.18 necromancer got a large buff where the arcane attack now deals 19x2 damage to undead and 16x2 to normal units, further confirming the point in section 2 about specialist attacks becoming flattened into generalist ones)

Mermaid Diviner: 12x4 against skeletons - 48 total (meanwhile with the 1.18 resistances it is 10x4 - 40 total)

1.16 Enchantress: 13x4 against skeletons, 52 total (meanwhile with the 1.18 resistances and 1.18 damage she got ridiculously overbuffed to the point that she deals MORE damage to skeletons - 17x4 while also dealing 13x4 to non-undead, as much as she used to deal to undead with -50% arcane resistance)

Spectre: 13x4 against skeletons, 52 total (meanwhile with the 1.18 resistances it is 11x4 - 44 total)


examples of non-arcane units attacking units with weaknesses to their attack:


level 3 examples:

Drake Blademaster/Drake Warden blade: 21x3 against elusivefoot units - 63 total

Inferno Drake: 12x6 against woses - 76 total (or more moderate example - 10x6 vs skeletons - 60 total)

Iron Mauler/Ancient Wose against Skeletons: 30x2 - 60 total

1.16 Grand Knight against elusivefoots and cavalry (with charge special active) - 41x2, 82 total

1.18 Grand Knight against elusivefoots and cavalry (with charge special active) - 46x2, 92 total

1.16/1.19 elvish sharpshooter against elusivefoots: 12x5, 60 total 

Lich against Drakes (cold attack): 18x3, 54 total

1.18 necromancer against drakes (cold attack): 28x2, 56 total

Arch Mage against woses: 18x4, 72 total

Nightgaunt against elusivefoots (with backstab special active) - 26x3, 78 total




level 4 arcane examples:

1.16 sylph: 15x5 against skeletons - 75 total (meanwhile with the 1.18 resistances and 1.18 damage she got ridiculously overbuffed to the point that she deals MORE damage to skeletons - 20x5 while also dealing 16x5 to non-undead, as much as she used to deal to undead with -50% arcane resistance)

ancient lich arcane: 13x5 against skeletons - 65 total (meanwhile with the 1.18 resistances it is 11x5 - 55 total)


level 4 non-arcane examples:


ancient lich cold: 19x5 against drakes - 95 total

armageddon drake: 18x6 against woses - 108 total


"But what about level 2 units?" You may ask, here are some comparisons too:

level 2 arcane units:

White Mage: 13x3 against skeletons - 39 total (meanwhile with the 1.18 resistances it is 11x3 - 33 total)

Elvish Sorceress: 12x4 against skeletons - 48 total (meanwhile with the 1.18 resistances it is 8x4 - 32 total)

Wraith: 9x4 against skeletons, 36 total (meanwhile with the 1.18 resistances it is 7x4 - 28 total)


level 2 non-arcane examples:

Shock Trooper: 22x2 against skeletons - 44 total

Drake Warrior/Drake Arbiter/Dwarvish Steelclad against elusivefoots: 14x3, 42 total

Shadow against elusivefoots (with backstab special active): 21x3 - 63 total

Marksman against elusivefoots and cavalry: 11x4 - 44 total

Knight against elusivefoots and cavalry (with charge special active): 34x2 - 78 total

Lancer against elusivefoots and cavalry (with charge special active): 29x3 - 87 total

Red mage againt woses: 12x4 - 48 total


In conclusion - even with the old resistances, due to arcane attacks generally having lower base damage numbers than other damage types, even against undead arcane did not reach the same max power as some other non-arcane DPS units were able to achieve. It was not overpowered, it was balanced around arcane units being more specialized. And now with the flattened resistances, the result is that arcane units either became underpowered or had to have their base damage buffed to the point of being a generalist DPS unit.

2024-11-17 13:07 UTC, dashomew commented
I totally agree with point 2.

I am all for a revert to happen.

Anyways... if i had to deal with it, here are my suggestion:

Keep 1.18 - Ogres: [1.16] 20%, [1.18] 10%.  

Revert 1.16 - Humans: [1.16] 20%, [1.18] 10%.

Keep 1.16 or -20% Compromise - Drakes: [1.16] -30%, [1.18] -10%.

Keep 1.16 or -40% for lvl1s and -30% for lvl2s Skeletons: [1.16] -50%, [1.18] -20%.

Keep 1.18 or Fighter 10% and Mages 20% or viceversa - Saurians: [1.16] 20%, [1.18] 10%.

I think having goblins 10% arcane would be interesting, to "separete" them from Orcs (0%).

Great Job by Forest Dragon!

2024-11-17 14:41 UTC, Dalas121 commented
Glad you're acting on this. I agree that the 1.18 stats are a problem for all the reasons you and others have echoed.

However, I'm also not entirely comfortable with -50%/+20%. With a full reversion to 1.16, I worry that arcane attacks will be too powerful in typical situations and campaigns. I would rather see arcane be more specialized, with arcane units falling back on their other abilities/attacks against non-vulnerable targets. To quote Jonathan-Kelly from my old mages PR:

![Untitled](https://github.com/user-attachments/assets/54e9703d-e1b9-4037-81c6-52cb0403a30f)

In a campaign vs "evil" enemies, arcane-dealing units are either incredible (-50% undead) or good (0% orcs). In a campaign where you fight all enemies evenly, the 20% resist from humans is outweighed by the -10%/-30%/-50% resists of elves/trolls/drakes/undead.

I feel arcane would be best-designed if it's very powerful in some common situations, but is correspondingly anemic in other *common* situations.

One option could be raising Orcs to 20% arcane resist. I feel that would make them a reliable weakness of arcane, but such a change could certainly affect UMC. Another option could be nerfing arcane-damage units below their 1.16 values so that while they'd still deal massive damage vs Undead, they'd deal less damage vs Orcs and much less vs Humans/Saurians/etc.

2024-11-17 15:09 UTC, Mirion147 commented
So, I can't help but notice several glaring holes in your very extensive and specifically constructed PR.

Units listed in regards to the arcane damage pre and post 1.18 which are healer/utility units:
MoL, Paladin (falls within this, though the damage is much closer since it's much less of a utility unit), Mermaid Diviner, and White Mage.

These are not the equivalent units to Drake Blademaster/Warden, Inferno Drake, Iron Mauler, Grand Knight, Elvish Sharpshooter (you put 1.19 but I'm guessing you meant 1.18 since the damage was nerfed in 1.19), Lich, Necromancer, Arch Mage, Nightgaunt, Slyph, Ancient Lich, Armegeddon Drake, Shock Trooper, Drake Warrior, Shadow, Marksman, Knight, Lancer, and Red Mage.

You listed 4 utility units (1 of which is, to be fair, only partial utility), against 20 Specialized damage dealing units, no utility about them.

To also be fair, you listed other non utility units:
Lich, Necromancer, Enchantress, Spectre, Sylph, Ancient Lich, Elvish Sorceress, Wraith

8 damage units. However 2 of them have already been changed in 1.19: Enchantress 1.19 11x4, Sylph 1.19 13x5
So there are only 5 damage dealing units that you're referencing that are accurate and have a problem, vs 19 accurate damage dealing units that are fine.

Let's go through the damage dealing units in their current setup:
Enchantress vs Skeletons: 52 damage(1.19) and 56 damage(1.16) (changed from a buff to a nerf in #8741 by ForestDragon)
Sylph vs Skeletons: 80 damage(1.19) and 60 damage(1.16) (buff reduced in #8741 by ForestDragon)
Ancient Lich vs Skeletons: 55 damage(1.18) and 68 damage(1.16) (nerf)
Lich vs Skeletons: 42 damage(1.18) and 54 damage(1.16) (nerf)
Necromancer vs Skeletons: 38 damage(1.18) and 36 damage(1.16) (buff)
Spectre vs Skeletons: 44 damage(1.18) and 56 damage(1.16) (nerf)
Elvish Sorceress vs Skeletons: 32 damage(1.18) and 44 damage(1.16) (nerf)
Wraith vs Skeletons: 28 damage(1.18) and 36 damage(1.16) (nerf)

So out of these 8 units, 1 of them was made into a nerf after being a buff, and 2 more were buffed, leaving damage dealing 5 units that were nerfed in 1.18/19.

So where did the utility units fall before the arcane change vs non arcane vulnerable units?
Paladin in 1.16 would deal 30 damage vs humans and saurians, and 40 damage vs elves/orcs/merfolk/naga (all 0% resist).
Paladin in 1.18 does 40 vs humans and saurians and 45 vs 0 resist units (worth noting that GK deals 48 damage to 0 resists units 40 damage vs 20% resists, and 64 damage vs units with -30% resists). This makes Paladin more viable, and doesn't make it outshine the GK outside of a few specialized situations. Much more playable.
MoL in 1.16 would deal 30 damage to 20% resists, and 36 damage to 0 resists.
MoL in 1.18 deals 33 damage to 10% resists, and 36 damage to 0 resists (outside of turning Mage of Light into a Avenging Angel Undead Fighter, the MoL is barely changed, but receives a small buff in damage).
WM in 1.16 would deal 21 damage to 20% resists, and 27 damage to 0 resists.
WM in 1.18 deals 24 damage to 10% resists, and 27 damage to 0 resists (same deal as with Mage of Light, small buff, essentially no change).
M Diviner in 1.16 would deal 24 damage to 20% resists, and 32 damage to 0% resists.
M Diviner in 1.18 deals 28 damage to 10% resists, and 32 damage to 0% resists (same deal)

So the only changes not related to the arcane rework with these units is a positive one for the Paladin.

Meanwhile damage dealers vs non arcane vulnerable units:
Enchantress in 1.16 28 damage(20%) and 36 damage(0%)
Enchantress in 1.18 40 damage(10%) and 44 damage(0%) (This is a buff which essentially makes the faction capable of dropping the mage line from it's faction lineup, there has already been talking about removing the mage line, now it's more possible than ever).
Sylph in 1.16 40 damage(20%) and 50 damage(0%)
Sylph in 1.19 60 damage(10%) and 65 damage(0%)
Ancient Lich in 1.16 50 damage(20%) and 65(0%)
Ancient Lich in 1.18 60 damage(10%) and 65(0%) Ancient lich and Sylph on par with each other as prime level 4 units
Keep in mind that Great Mage in 1.16 is 52 damage to 20% fire resist and 64 damage vs 0% resist
Great Mage in 1.18 is 60 damage(10%) and 68 damage(0%)
Lich in 1.16 21 damage(20%) and 27 damage(0%) so would use cold attack 36 damage
Lich in 1.18 24 damage(10%) and 27 damage(0%) still uses cold 36 damage
Necromancer in 1.16 20 damage(20%) and 24 damage(0%) would use cold attack 34 damage
Necromancer in 1.18 28 damage(10%) and 32 damage(0%) would still use cold attack now at 38 damage (still less than Enchantress)
Spectre in 1.16 28 damage(20%) and 36 damage(0%)
Spectre in 1.18 32 damage(10%) and 36 damage(0%) (this unit's already got low damage because of drain, so comparing it with something like blademaster vs wose is misleading to say the least, even without using backstab at 0% resists the nightgaunt does 30 damage, having the potential to do 78 damage vs elusive foot)
Wraith in 1.16 20 damage(20%) and 24 damage(0%)
Wraith in 1.18 20 damage(10%) and 24 damage(0%) literally the same, so only got a nerf against undead
Elvish Sorceress in 1.16 24 damage(20%) and 28 damage(0%)
Elvish Sorceress in 1.18 24 damage(10%) and 28 damage(0%) literally not changed, so this damage dealer only got a buff vs skeletons.

So the question is, what is the actual problem?
Elves have already been adjusted, So using the Sylph and Enchantress damage values to justify this change (and using the sharpshooter as comparison) are misleading and dishonest.

The changes that keep utility units from being utilized as damage dealers? This is, I believe, a debate worth having, but it needs to be its own debate and not mixed in like just another piece of the pie.

Some damage dealers are underperforming (Lich, Wraith, Spectre, Elvish Sorceress) because they didn't receive a buff to compensate the change, but still have to deal with the consequences of the change. (I guess you could argue for Ancient Lich here as well, but he seems fine to me. 
 
 Is a full revert actually necessary? You want to make authors change BACK to their previous versions when the people who had an issue with it have already modified their content to not have to worry about it (as you noted) and others are fine with leaving the changes be, or have already adjusted their content.

2024-11-17 15:44 UTC, MrTitainin commented
I think we should take Dashomew's resistances, which make much more sense, and set damage values accordingly - in particular, you're definitely over-nerfing Enchantress/Sylph against non-undead enemies. I'm also against paladin and necromancer damage nerfs at all.

You mention EoMa - note that it does not have -50% arcane on Destroyers. It's just too high for a faction-wide weakness.
It definitely makes sense for ud to be arcane-susceptible lore-wise, but exact value is subject for fine-tuning. Had arcane been a weaker second attack for all units affected like with DA line it'd be fine, but with elves having only one proper mage unit with main damage being arcane, it should not be too weak against most factions in the game.

The whole PR is based on a few important points, but then takes everything to extreme and as such, it's undesirable and missguided.

2024-11-17 16:15 UTC, Hejnewar commented
Balance team vote failed 2 in favour and 3 against.

2024-11-17 16:54 UTC, kameramen0106 commented
> @Hejnewar Balance team vote failed 2 in favour and 3 against.

Could you please answer the following question?

1. why did the balance team reject this proposal?
2. is it this proposal as a whole or in part?
3. in addition, what is your position or opinion?

All of this is opaque in a single line of replay.

I do not accept this attitude of replaying without providing specific arguments and opinions. In my eyes, you seem to want to end this discussion quickly.

But I would like to emphasize. **At this stage, this discussion is still uncertain.** You are being disrespectful to those who are looking for a polite discussion.

2024-11-17 16:54 UTC, Roge-Tebnelok commented
> Balance team vote failed 2 in favour and 3 against.

The PR was created on this day, and the team has already voted without giving at least a week for those who are interested in participating in balance discussions to express their opinion? Arcane rework is too important to be handled like this, what reasons were discussed by the team already to do that?

2024-11-17 17:14 UTC, Dalas121 commented
To add some context - this vote was held yesterday, before this PR existed. The vote was held alongside several others, along the lines of _"what's our opinions on these"_ rather than _"should we make this specific change"_.

I think it should be fine to give this PR some more time for discussion, and then later hold another vote specifically about approving/denying this PR.

2024-11-17 18:19 UTC, Hejnewar commented
@Dalas121 

> To add some context - this vote was held yesterday, before this PR existed. The vote was held alongside several other votes, and my understanding is it was more about "what's our opinions on these" rather than "should we make this specific change".

 "Should Arcane Resistance Rework be reverted?"
 
 This was literally the question, because I wanted to know what ground I stand on. Yes this wasnt about this PR exactly but this is PR pretty much that. Finally, 2 members already stated that they have their own plans for this here so I dont think it _these specific changes_ have any chances. Also sorry but if you dont take votes seriously, thats on you. Vote should be something serious after all.

2024-11-17 18:53 UTC, Dalas121 commented
> Also sorry but if you dont take votes seriously, thats on you. Vote should be something serious after all.

_"Should Arcane Resistance Rework be reverted?"_ doesn't actually specify which changes are being proposed. For example, the Corpse/Soulless weren't included in the original arcane PR, nor were related units like the Enchantress/Sylph or Paladin, but they're certainly related.

Given the vagueness of the original question, even if the poll had passed I think we would have still needed to create and vote on a PR with specific line-by-line changes.

2024-11-17 22:55 UTC, Mirion147 commented
V🌌V BGGV CFg

2024-11-17 23:50 UTC, Discontinuum commented
Arguments behind these PR are solid, hard to add anything. I agree that the new arcane damage lost its flavour without clearing benefits. The change also rendered the notice about "arcane dealing tremendous amount of damage to magical beings" not really true (fire and even impact deals the same to Skeletons right now). My only addition (if it hasn't been mentioned already) would be that great range of values isn't a bad thing per se: many damage types range a lot, for example pierce goes from -20% to +60%, blade ranges from -30% to +50%. Arcane's range was made a lot narrower now, but it's not a good thing per se, without any other reasons.

Regarding the vote that apparently took place even before this PR appeared, I would advise the Balance team to hold more discussions on this contentious topic. As I understand from further clarifications, it was some kind of vote on the initial state from which the balacing would start. There is still a long road ahead. Considering that the issue has wide support and even support of one Balance team members, it should definitely be worked on in detail during balancing. It would be nonconstructive to try close such broad questions in one day in one vote.

2024-11-18 07:31 UTC, babaissarkar commented
Despite not very good at balancing, I also support this, partly because how many umc campaigns were affected and at worst, broken, my own included. (had to copy many unit stats over and partly replace arcane with my own type.)

2024-11-18 13:16 UTC, knyghtmare reviewed
This is certainly a very heated discussion. 

I am in support of a revert, but a majority revert and not a full one. Like, we are talking about maybe 65%-80% reversions. Like I am on board to some exceptions and reversion of the problematic cases.

Lastly, the minority case discussions:

- Elf Enchantress, Elf Sylph and Necromancer stat/designs are being disputed (discussed) in a prior PR #9300. I think these three should be discussed outside this PR (as in make a new PR on these 3 cases, or 3 PRs for each case to be handled individually) 

- Ogres keeping their 10% arcane RES (as mentioned by @dashomew). I am on board with it. Ogres are quite sturdy punching bag units, so that revert to 20% might make them slightly stronger in SP content. The Ogre level 2 is in AoH as a recruiting option for Loyalists, but that's a topic for another day, I believe.

- Saurians (Keeping at 10% arcane seems fine). They are pretty good in their gender segregated unit roles already.

- For The Undead and Drake cases, the compromises offered by Dashomew seem good to consider. Might be satisfactory to both parties. I would not complain if a reversion happens for these as well.

2024-11-18 13:28 UTC, knyghtmare commented
I would also add that among the "Elf Enchantress, Elf Sylph and Necromancer stat/designs are being disputed" cases, Necromancer is the most heavily discussed one, thus, I think it's in the best interests of UMC, developers, and community for the problem cases to be discussed in their own dedicated PR.

2024-11-18 14:32 UTC, kameramen0106 commented
Generally, your opinion seems positive to me as well. However, for undead arcane, I believe that this resistance should be consistent and equal at all levels. This is because I feel that it makes almost no sense for the arcane weakness to be overcome even slightly at higher levels. It seems rather unnatural, besides not good from the gameplay sense. In other words, ideally, -50% would be desirable, as the 1.16 stats. However, I would also suggest -40% as the minimum compromise.

2024-11-18 14:44 UTC, Roge-Tebnelok commented
> Generally, your opinion seems positive to me as well. However, for undead arcane, I believe that this resistance should be consistent and equal at all levels. This is because I feel that it makes almost no sense for the arcane weakness to be overcome even slightly at higher levels. It seems rather unnatural, besides not good from the gameplay sense. In other words, ideally, -50% would be desirable, as the 1.16 stats. However, I would also suggest -40% as the minimum compromise.

Agreed. Another reason is that the higher the unit's level, the harder it becomes to kill, and unless unit isn't supposed to become more resistant to their weak type, like Sorceress line or Arcane Enforcer in TDG, the examples that first came to mind, this shouldn't be the case, and their vulnerabilities shouldn't change between levels.

2024-11-18 15:43 UTC, Jonathan-Kelly commented
Since the majority of the balance team favors mostly reverting the arcane resistances rather than mostly keeping them, why not just merge this PR as a starting point? Why not work forward from the much firmer ground of 1.16  which was thoroughly play tested for years in highly competitive tournaments, has years of content built on it and has the support of the community behind it?

2024-11-18 15:53 UTC, Mirion147 commented
I really don't think this PR has any actual direction other than "1.18 ARCANE BAD! *BAM* *BAM*"

I'll ask my questions again.
What is the problem? 
Elves have already been adjusted, So using the Sylph and Enchantress damage values to justify this change (and using the sharpshooter as comparison) are misleading and dishonest. So what are you looking for with them? They would need to be changed yet again. 

The changes that keep utility units from being utilized as damage dealers? This is, I believe, a debate worth having, but it needs to be its own debate and not mixed in like just another piece of the pie.

Some damage dealers are underperforming (Lich, Wraith, Spectre, Elvish Sorceress) because they didn't receive a buff to compensate the change, but still have to deal with the consequences of the change. (I guess you could argue for Ancient Lich here as well, but he seems fine to me.

Is a full revert actually necessary? You want to make authors change BACK to their previous versions when the people who had an issue with it have already modified their content to not have to worry about it (as you noted) and others are fine with leaving the changes be, or have already adjusted their content.

Also 3 members of the balance team are against this change, so I'm not sure how that equals a majority being in favor.

2024-11-18 16:01 UTC, Roge-Tebnelok commented
> I really don't think this PR has any actual direction other than "1.18 ARCANE BAD! _BAM_ _BAM_"
> 
> I'll ask my questions again. What is the problem? Elves have already been adjusted, So using the Sylph and Enchantress damage values to justify this change (and using the sharpshooter as comparison) are misleading and dishonest. So what are you looking for with them? They would need to be changed yet again.
> 
> The changes that keep utility units from being utilized as damage dealers? This is, I believe, a debate worth having, but it needs to be its own debate and not mixed in like just another piece of the pie.
> 
> Some damage dealers are underperforming (Lich, Wraith, Spectre, Elvish Sorceress) because they didn't receive a buff to compensate the change, but still have to deal with the consequences of the change. (I guess you could argue for Ancient Lich here as well, but he seems fine to me.
> 
> Is a full revert actually necessary? You want to make authors change BACK to their previous versions when the people who had an issue with it have already modified their content to not have to worry about it (as you noted) and others are fine with leaving the changes be, or have already adjusted their content.
> 
> Also 3 members of the balance team are against this change, so I'm not sure how that equals a majority being in favor.

You repeat the same arguments. And the vote happened before PR, the vote on PR itself didn't happen yet.

2024-11-19 09:01 UTC, ForestDragon-wesnoth commented
Thanks to knyghtmare for pointing out the walking corpse/soulless mistake! fixed it with the latest commits

For Enchantress/Sylph/Necromancer, although their effectiveness is directly tied to arcane resistances, keeping that part of the discussion in separate PR can work, especially considering PR #9300 reduces the aforementioned units' damage too.

So I have now removed the enchantress/sylph/necromancer reverts from this PR for now, leaving only the Paladin revert which is not covered by PR #9300

As for the other suggestions, for now I want to wait for more people to comment before making a decision, considering the importance of this topic and the interest in it by the community.

2024-11-19 14:47 UTC, CelticMinstrel reviewed
As always, I do not support "reverting" any balance changes. The specific changes in this pull request (particularly after Knightmare's review) _may_ be fine (I'm not planning to look at them myself), but I don't support anything like a full revert or even a "partial" revert.

2024-11-19 15:03 UTC, soliton- commented
It was not a balancing change. You can read the first post yourself or the linked forum thread. As far as I'm concerned it was a "make arcane less distinctive" change with no understandable reasoning.

2024-11-19 15:19 UTC, Jonathan-Kelly commented
> As always, I do not support "reverting" any balance changes. 

Balance changes get reverted all the time in well maintained games. Especially changes like this which were put into 1.18 without any real testing.

2024-11-19 15:30 UTC, kameramen0106 commented
> As always, I do not support "reverting" any balance changes. The specific changes in this pull request (particularly after Knightmare's review) _may_ be fine (I'm not planning to look at them myself), but I don't support anything like a full revert or even a "partial" revert.

I think that when posting the comment and participating in the discussion like this, you need to check the facts and provide your opinion and rationale clearly. I believe that is the premise and such very brief opposing comment confuses me.

> I'm not planning to look at them myself

Please look at them yourself, as they concern the future of Wesnoth.

> It was not a balancing change. You can read the first post yourself or the linked forum thread. As far as I'm concerned it was a "make arcane less distinctive" change with no understandable reasoning.

I greatly agree with your opinion.

> Balance changes get reverted all the time in well maintained games. Especially changes like this which were put into 1.18 without any real testing.

Good point. I think reverting is much needed as an option.

2024-11-21 17:04 UTC, HolyPaladin1 commented
I would recommend undead to be more vulnerable to arcane attacks, as it was before 1.18. That would improve fitting their race to  established lore and mechanics.

2024-11-21 17:27 UTC, Roge-Tebnelok commented
> As always, I do not support "reverting" any balance changes. The specific changes in this pull request (particularly after Knightmare's review) _may_ be fine (I'm not planning to look at them myself), but I don't support anything like a full revert or even a "partial" revert.

Why are you against turning back to something that caused fewer complaints, it's not even giving it a chance, as it has been already proven as a working option, hasn't it? 1.18, on the other hand, is a wasted opportunity to achieve something undisclosed without presenting it beforehand. What's about it that you cling to so tightly?

2024-11-21 19:36 UTC, ForestDragon-wesnoth commented
@dashomew Hello, thanks for reviewing my PR! I was a bit busy with some irl things this week, but now that I got a bit more time, here are my thoughts on your suggestions:

I agree with you that humans would be better off with 1.16 resistances

for drakes/saurians/ogres I would like to first see what other people think on the matter first, but these compromises could work if the undead maintain their original identity

But as for the undead idea of -40% on lvl1 but -30% on lvl2-3, I believe that is not the best approach to address the underlying problems

If the concern is about level 2 leaders in PvP, Undead have access to two arcane resistant leader options which they can use against factions with access to arcane - Dark Sorcerer and Necrophage (especially if their arcane gets reverted from 10% to 20%)

The wide backlash against the arcane rework is from many of both MP players/modders and SP players/modders. And SP has more lvl2-3s and less lvl1s. So the result is that MP Players get a more popular compromise of -40% resistances, while SP Players would be stuck with -30% which is much closer to 1.18's -20% than the -50% many want. The majority of players play SP content, so I think that shouldn't be neglected.

Only undead has access to lvl1 arcane units, and Drakes, Knalgan Alliance, Northerners and Dunefolk factions have no access to any arcane-damage dealing units of any level. I think a slight advantage in the rebels/loyalist matchup against specific leaders, or slight advantage in a mirror matchup, doesn't seem worth sacrificing SP Players' enjoyment of the arcane damage.

2024-11-22 12:29 UTC, kameramen0106 commented
> for drakes/saurians/ogres I would like to first see what other people think on the matter first, but these compromises could work if the undead maintain their original identity

Basically, I am neutral on these compromises, and in some ways agree with the opinion by ForestDragon. That is, I am fine with these compromises, at least as long as the arcane resistance of the undead is reverted back to the 1.16 stats of -50% (or -40%), with no change by level. If I may add, -30% would be better for the drakes, but that is also not my opinion that it should be that way at all costs.

2024-11-22 19:15 UTC, Roge-Tebnelok commented
> > for drakes/saurians/ogres I would like to first see what other people think on the matter first, but these compromises could work if the undead maintain their original identity
> 
> Basically, I am neutral on these compromises, and in some ways agree with the opinion by ForestDragon. That is, I am fine with these compromises, at least as long as the arcane resistance of the undead is reverted back to the 1.16 stats of -50% (or -40%), with no change by level. If I may add, -30% would be better for the drakes, but that is also not my opinion that it should be that way at all costs.

Agreed, though saurian augur and skirmisher lines should probably have equal arcane resistance, as it is in other races with both fighters and mages.

2024-11-23 07:37 UTC, Refumee commented
> > > for drakes/saurians/ogres I would like to first see what other people think on the matter first, but these compromises could work if the undead maintain their original identity
> > 
> > 
> > Basically, I am neutral on these compromises, and in some ways agree with the opinion by ForestDragon. That is, I am fine with these compromises, at least as long as the arcane resistance of the undead is reverted back to the 1.16 stats of -50% (or -40%), with no change by level. If I may add, -30% would be better for the drakes, but that is also not my opinion that it should be that way at all costs.
> 
> Agreed, though saurian augur and skirmisher lines should probably have equal arcane resistance, as it is in other races with both fighters and mages.

I agree with Roge. Saurian Augur and skirmisher should have the same resistance.

I believe that Augurs are just tribal mages/shamans, that implies for me that they are not so well versed as a mage who studies magic or a elf that lives for centuries.

Augurs study magic out of boredom while guarding eggs and only using cold and healing magic. I believe that they have no clue about arcane magic.

That's my reasoning. I dont see any saurian lore that supports different arcane resistances.
I would rather say, give Augurs a higher cold resistance, but that isn't necessary as well.

A full revert for the saurians is not necessary in my eyes. I would prefer to push the revert on the undead. In my opinion arcane damage should hurt magical creatures a lot.

2024-11-23 07:47 UTC, Mirion147 commented
Is there something I missed, cause everywhere I've looked, all saurians have the same exact resistances as each other...? Who is saying they should be different?

I'm also yet to hear what the actual goal of this is.

2024-11-23 08:18 UTC, kameramen0106 commented
> Is there something I missed, cause everywhere I've looked, all saurians have the same exact resistances as each other...? Who is saying they should be different?

10% Skirmishers 20% Augurs was a suggestion by dashomew, one of the balance team members. And 1.16 and 1.18 saurians both have identical arcane resistances.

2024-11-23 12:34 UTC, ForestDragon-wesnoth commented
After listening to suggestions from the balance team members and members of the community who participated in the discussion, I have decided to implement the following adjustments to the PR:

Drakes: arcane from -30% to -20%, Fire Wisp/Guardian/Wraith remain at -30% arcane due to being fully magical beings

Ogres: arcane from 20% to 10%

Saurians: arcane from 20% to 10%

2024-11-23 17:01 UTC, CelticMinstrel commented
> I think that when posting the comment and participating in the discussion like this, you need to check the facts and provide your opinion and rationale clearly. I believe that is the premise and such very brief opposing comment confuses me.

I think you need a much stronger rationale for reverting a change than you need for merely making a change. I'm not directly opposing the changes made here, but I am opposed to the manner in which they're presented as a revert. To me that implies the change hasn't really been thought through properly – it's like you're making the change out of nostalgia rather than a desire for improvement.

> Please look at them yourself, as they concern the future of Wesnoth.

There really is little point. I'm probably one of the worst people to ask about balance changes. Normally I would glance over things from a lore standpoint, but there doesn't seem to be any point in this case.

2024-11-23 18:32 UTC, kameramen0106 commented
> I think you need a much stronger rationale for reverting a change than you need for merely making a change. I'm not directly opposing the changes made here, but I am opposed to the manner in which they're presented as a revert. To me that implies the change hasn't really been thought through properly – it's like you're making the change out of nostalgia rather than a desire for improvement.

Taking this comment of yours as a totality as it is, it seems to me that you are disagreeing from the perspective that this PR is a revert. I am not saying that I am entirely unable to understand that concern. But what is most problematic is the fact that many people actually feel that there are issues and negative effects to the arcane changes for 1.18. That is clearly evident if you read this PR in order from the beginning. Those community opinions are too significant to be ignored. And I consider those to be enough to make a stronger rationale.

> There really is little point. I'm probably one of the worst people to ask about balance changes. Normally I would glance over things from a lore standpoint, but there doesn't seem to be any point in this case.

I believe that participating in discussions about such important topics comes with a reasonable amount of responsibility, especially for people with some authority over the game. And, I still believe you would be more persuasive if you checked the details of this topic yourself and then offered your thoughts. However, that is only my opinion.

2024-11-23 18:45 UTC, Refumee commented
> > I think that when posting the comment and participating in the discussion like this, you need to check the facts and provide your opinion and rationale clearly. I believe that is the premise and such very brief opposing comment confuses me.
> 
> I think you need a much stronger rationale for reverting a change than you need for merely making a change. I'm not directly opposing the changes made here, but I am opposed to the manner in which they're presented as a revert. To me that implies the change hasn't really been thought through properly – it's like you're making the change out of nostalgia rather than a desire for improvement.
> 
> > Please look at them yourself, as they concern the future of Wesnoth.
> 
> There really is little point. I'm probably one of the worst people to ask about balance changes. Normally I would glance over things from a lore standpoint, but there doesn't seem to be any point in this case.
> 

Isn't reverting a change not the same as making a change?

Maybe I can give you some information about the change, if you read it.

Firstly the forum thread:
https://forums.wesnoth.org/viewtopic.php?t=57075

4 comments
2 from hej
2 from other user

I will only reflect the other users feedback.

SkyEnd made a meme that fire damage is the same as arcane damage.

Ravana supports the change causw arcane will loose its importance and the special note should be removed too.
I am not 100% if Ravana was sarcastic.


Now to the PR:
https://github.com/wesnoth/wesnoth/pull/7801

13 comments (now compare this now to this with 81 comments right now I believe)

Here you can see that people having concerns with it, but those concerns are denied with no obvious reasons.

Even one stated that he rewrites drake lore, so it fits the arcane rework. Was that sarcastic too? I hope so, I don't wanna see lore changes that quickly put of nowhere.

I missed the Agenda of the PR, here a partly quote "better fit the growing needs of PvE and PvPvE"
Now, PvE players dislike the change the most.

And the reasoning is that arcane resistance is quite varied like cold, but cold can be ignored. Enough said...

I hope this helps you understand the whole PR change revert however you are calling it.

2024-11-23 19:54 UTC, Roge-Tebnelok commented
> > I think that when posting the comment and participating in the discussion like this, you need to check the facts and provide your opinion and rationale clearly. I believe that is the premise and such very brief opposing comment confuses me.
> 
> I think you need a much stronger rationale for reverting a change than you need for merely making a change. 

If the change that is being reverted doesn't have a strong rationale, reverting it isn't really more difficult than changing something new. The strength of the point can only be determined by comparison, and so far there has been not enough proper justification for 1.18 arcane rework, both in this discussion and in the discussions when it was originally made. Many players, modders and some developers do not understand/agree the original explanation for the arcane rework. To quote soliton: 
> It was not a balancing change. You can read the first post yourself or the linked forum thread. As far as I'm concerned it was a "make arcane less distinctive" change with no understandable reasoning.

>I'm not directly opposing the changes made here, but I am opposed to the manner in which they're presented as a revert. To me that implies the change hasn't really been thought through properly – it's like you're making the change out of nostalgia rather than a desire for improvement.

Undead and Drakes didn't even need to be more resistant to arcane in competitive, as level 2 units aren't as common there, and only Ghosts and Dark Adepts have arcane attack on level 1, in campaigns, arcane specialists are more common, but now they aren't better than specialists in other types. 
There's nothing wrong in nostalgia, in fact, it shouldn't be disregarded as it is what keeps seasoned players in game. Also reverting the balance change that made things worse from the previous better state is a significant gameplay improvement on its own, and old arcane and the change back to it is thought of and through more highly and properly than 1.18 arcane rework judging by discussions around it. 

> > Please look at them yourself, as they concern the future of Wesnoth.
> 
> There really is little point. I'm probably one of the worst people to ask about balance changes. Normally I would glance over things from a lore standpoint, but there doesn't seem to be any point in this case.

How does onesided gameplay change that made arcane vulnerability equal to fire or impact on skeletons or to pierce on drakes or resistance of simple creatures which isn't really protecting them make any sense from lore standpoint than higher vulnerability on magical creatures resistance on mundane units? Also, the stats reflect the lore in some way, and even if lore itself isn't mentioned in balance discussion, which isn't really true in this PR, it doesn't mean it can be skipped as unrelated to lore.

2024-11-23 21:10 UTC, OrekOrek commented
For Fire Wisp/Guardian/Wraith, it probably makes more sense to change the arcane resistance of the newly introduced "flamefly" movetype in #9438 “Increase Fire Resistances of Fire Guardian Line” if we agree to adopt this new movetype.

2024-11-24 01:07 UTC, Jonathan-Kelly commented
Quoting @Dalas121
> In a campaign vs "evil" enemies, arcane-dealing units are either incredible (-50% undead) or good (0% orcs). In a campaign where you fight all enemies evenly, the 20% resist from humans is outweighed by the -10%/-30%/-50% resists of elves/trolls/drakes/undead. Even worse, the most common 20% resist enemies (bandits and saurians) have many high-defense units - vulnerable to magical arcane attacks.

> I feel arcane would be best-designed if it's very powerful in some common situations, but is correspondingly anemic in other common situations.

I may have a solution for you that will not upset the community while making campaigns generally more interesting - significant new `race=mechanical` units with very high arcane resistance.

Specifically, orcish (and human) [siege engines](https://en.wikipedia.org/wiki/Siege_engine) and warships. Big, slow moving, high level (think 4-9) strategic/boss units with real ranged attacks, area of affect attacks, massive durability and/or powerful attack damage. This is something I have already begun working on to enhance WoF, DW, and the many orc antagonist focused campaigns (starting with NR).

2024-11-26 18:12 UTC, Jonathan-Kelly commented
@Dalas121 
> I'm not sure if this can be a full solution to arcane unless some of these siege engines actually get in mainline (which will be mostly dependent on art/doofus), but I do support the direction.

I might be able to help with that, since I am already working on a medieval [warship](https://github.com/wesnoth/wesnoth/pull/9600#issue-2684703348) with the same wooden/mechanical look as a siege engine. And for campaigns, the art requirements seem to be less stringent than core, fortunately.

The arcane resistance for mechanical units could be 80%, or even 100% (which we see with the Fire Dragon and Armageddon Drake when it comes to fire resistance).

2024-12-01 17:54 UTC, cooljeanius approved these changes

2024-12-01 17:57 UTC, cooljeanius commented on data/core/units/undead/Necromancer.cfg
> +        damage=13
reverted in fc114b6; this conversation can be marked as resolved.

2024-12-01 18:00 UTC, cooljeanius commented on data/core/units/elves/Enchantress.cfg
> +        damage=9
reverted in 7cbca6a; this conversation can be marked as resolved

2024-12-01 18:01 UTC, cooljeanius commented on data/core/units/elves/Sylph.cfg
> +        damage=10
reverted in 847777a; this conversation can be marked as resolved now.

2024-12-01 18:40 UTC, cooljeanius commented
I'll just note that I haven't tested any of my campaigns where the arcane resistances matter on 1.18 yet, so reverting them to their previous values would help reduce the amount of testing and I'd have to do for the campaigns I still haven't ported yet...

2024-12-03 12:03 UTC, Tezereth commented
I very much agree on the arcane revert

Such a huge change that sullies the place of Arcane among the damage types, but also it's place in the world from a thematic and world perspective, should not have ever happened, ESPECIALLY not on a whim of a single person while the vast majority of the community was not even aware until the change was decided.

I don't like using that word, but the arcane change truly "bastardized" the damage type, rendering it as nothing more than a "watered down fire" (no pun intended) that's less comfortable to use than fire.

Both from a gameplay and world perspective, arcane was specifically designed to be the most unique damage type, it isn't without reason that most arcane user _were_ either healers or units who's arcane attack was either not their main attack and therefore somewhat weaker (ex : necromancer shadow wave is weaker that it's chill wave), or it was weaker than most other mages of the same level (Sylph old 10 x 5, > 50 damage, was weaker than grand mage 16 x 4 > 64 damage)

2024-12-09 22:44 UTC, ReynBolt commented
Btw, by reading this topic, it seems kinda curious to me that arcane topic resistance values have sides have with very different approach and points about how arcane should be designed. But at this post I will give my opinion about specific cases and in overall what could be a more fair between PVP and PVE.

**I personally find that arcane resistances values on this units should be set to this values, due multiple reasons**
- **Skeletons (all levels) at -30%** , believe me -30% is still a lot and only 10% higher than 1.18 post changes. You can still exploit this weakness in PVE or single player campaigns, and also if we consider that arcane units will most often hit harder, then skeletons will take damages close to 1.16 values between the arcane damage increase and slightly lowered arcane weakness. 
- **Drakes (all levels) at -20% or -10%** , the idea is that drakes takes a damage more close to 1.16 values from arcane attackers... but not melting them that lot against arcane, because that ruins their viability in lots of game modes.
- **Most humans at 10%** , trust me, in multiplayer environment (survivals, RPG, etc) , humans having 20% arcane resistance was instantly making almost any human based faction be notably better over orcs/elves, etc non-human factions because having that lot of arcane resistances means you take seriously less damage from one of the three mages types, which helps human army by a real lot, even with only 10% arcane resistance that's a fair advantage (more solid formations more often).
- **Saurians are fine at 10%** , no debate needed here.
- **Ogres are fine at 10%** , they don't regen like trolls but hey there is a significant difference between taking 90% of damage over 110% of damage, that's fair.
- **Goblins could be 10% to arcane**, they're already low HP and this help them to not get "nerfed" against the damage increase of some arcane damage dealers. It also helps them to differ a bit more from orcs.

Also I like the idea that units like paladin and some other deal way more damage, because they become more useful against factions like knalga which are hard to combat with only physical damage types. Also for example, paladins are forced to use the lance over swift-foots, so they're not completely the really best to fight knalga as 90% dmg dealt vs elusive foot is not as great as 130% damage dealt from grand knight, so both options are fair and viable in a knalgan setup.

Lastly, remember that player base really hates drakes and undead the most, those 2 do not have as many custom factions from add-ons or era authors as loy-knalga variations, even elves have way more variations or inspiration than drakes/undead that seem modders hate that much that extreme high arcane weakness flaw. My point is that arcane weaknesses shouldn't be too low because that ruins the fun by playing as that faction when you can't hide from arcane damage or not even being capable to deal with arcane damages in a whole faction.... which is the main reason why I liked the only -10% arcane weakness on drakes, because that small difference is enough to make them viable in a lot more of situations and scenarios.


I kind of understand that part of the player base wants arcane to be more drastic at lowest/highest damages, but hey, 90% damage to human s 130% at skeletons is fairly decent difference (like +1/2 more damage taken to skeletons in comparation of humans) , as well remarkably more different from elves that are just -10% arcane weakness.

So my conclusion is that between slightly increased arcane damage from some of arcane dealers and lowered arcane weakness at certain units just to make the arcane damage values (at countered things) remain almost untouched, but also arcane being more consistent against the entire rest.... and you're wondering, YO IPS BUT YOU'RE MAKING ARCANE being better at being good at everything, but the fix to that is just making arcane damage dealers be less XP efficient, so players picking to have good arcane damage as handicap would be overpaying XP's to get their intended arcane dealer which is worth it if player is facing things that requires arcane damage dealers and not highly recommended if you're fighting "regular" enemies that gets almost no bonus damage from arcane.

Well... that's my point of view, but if you want to just keep loyal to previous from 1.6 you could just add mods as requirement for the campaigns like something that suits back the original arcane damage and resistances to all units in that game mode... but remember that wesnoth is not just default and it's quite stinky that in many eras or things that tries to be fun if being mixed to default being methodic about not making them broken vs undead (or undead-like) but still not garbage against the entire rest.... it's the main reason why I personally liked the arcane rework, but I understand that negates 15 years of being like this like real long.

2024-12-10 16:26 UTC, Refumee commented
Yes it negates the work that is done in the last 15 years.
All the UMC authors of the past looked at 1.4 to 1.16 (in case of arcane) stats and tried (in my opinion) to balance out their units.

We also need to consider, who is balancing the old UMC faction? Is there even somebody? If not, the units will just fall of balance wise and are now clearly inconsistent with 1.18+ units.

I also dont believe that UMC authors dislike undead. It is quite hard to create undead or drake units in the current style. I tried so myself...
But creating new humans or dwarves is quite easy, a bit franken here a bit franken there. I know that from experience if creating saurian and Elvish sprites.

Just creating an addon that reverts all the stats to 1.16?
I dont like this approach.

I am more for make 1.18 changes an addon and see how many players play it.

Or better, find a reasonable balance, a lore reason anything that doesn't break all mainline campaigns and many UMC campaigns and eras at once.

I played LoW lately and I noticed here and there bugs. No playtesting happened here, I understand that devs are busy.
But I would like some playtesters with the new balance updates or changes.
I dont know.
Make a list, South guard played with new balance update, everything fine or that needs to be adjusted.

So what do I mean? What did I notice in LoW.
There was one mage that recruited drakes. Lvl 3 drakes.
Their cost was increased in 1.18. From 46 to 61 gold for the Drake Trasher for example. That's 15 gold less for the AI!
In short we beat him up and this was the easiest mission of this campaign, cause the gold wasn't adjusted.

And this is mainline! Changes should not break mainline campaigns.

2024-12-15 12:38 UTC, Mirion147 commented
What ReynBolt has suggested is certainly better than a revert. Very similar to what Dashamow said i think (my memory could be lying to me, I didn't double check so if I'm wrong just say that lol).

I am against differentiating orcs and goblins stats but the rest is acceptable. Just because stats used to be one thing doesn't make that a reason for something to stay. There are many avenues available to get the same desired feel and making things interesting, while not forcing undead to deal with massive damage buffs.

I'm still not sure what the actual goal of this pr is, but if we're just looking to make arcane different than what it is: outside of goblins, I don't see an issue with the above proposal.

2025-01-17 22:50 UTC, spixi requested changes
Hi, when you are already working on the Walking Corpse, can you also please perform the macro simplification done here to make it consistent with the Soulless? https://github.com/wesnoth/wesnoth/commit/1dd72e709af9ef51f2f467c9e8083a299e934858
You can blame me, because I introduced that dirty hack with ~NOP, because I did not know that you can just write the macro parameter in quotes. Thank you a lot!

2025-02-02 21:24 UTC, ForestDragon-wesnoth commented
adjusted some movetypes to be more in line https://github.com/wesnoth/wesnoth/pull/9837
unfortunately it is 23:22 in my timezone at the moment and I have not been expecting such a situation, but I am open to adjusting more movetypes/stats to be closer to the balance team's wishes, and have been so in the past

2025-02-06 17:55 UTC, ForestDragon-wesnoth commented
Removed arcane=130 from the fire wisp line now that their arcane is handled by movetype, adjusted the initial post to more accurately reflect current stats

2026-05-19 23:53 UTC, Hejnewar commented
Closing this due to PR no longer being relevant (topic reaching conclusion in patches 1.19.14-15) and lack of discussion for over a year.

2026-05-19 23:53 UTC, closed without merging