Fix wesnoth.units.create_animator issues with direction
wesnoth/wesnoth pull request #9596
Opened 2024-11-20 18:44 UTC by Mahoyomu

### Goal of the PR
- Fix #9032, including make it possible to create moving animation similar to normal unit moving using the animator in lua. (where as initially there's teleport issue when using `impl_add_animation`, which is associated with #9163 and #9487)
### How does the PR work?
- By adding and updating facing direction change before and after running animation. (To make the target field work)
- By splitting out the generation of movement animation. (To keep the teleport issue from reoccurring at the same time)
### Does it resolve any reported issue?
- #9032
### If not a bug fix, why is this PR needed? What use cases does it solve?
- This is a bug fix, and maybe it also adjusts related features, to impl the not-working target field and add facing field.

## To do

Adjust possibly missed related method and changes I mistakenly made, remove redundant notes I used for quickly locating(all after this pr is nearly ready for review).

Merge the solution I made in #9487, so that I can leave the generation of movement animation to it.

Add and impl facing field, to handle the usage mentioned in #9032.

This PR is a Work In Progress.

## How to test
Compile and run, see the test video I might upload later if needed, or see changes in the src.

2025-01-16 07:22 UTC, Mahoyomu commented
This is the test video of recent commit:

https://github.com/user-attachments/assets/cae7594f-c197-49ff-b315-99790505f673

As the video shows, except for the bug that makes two units hidden after running the animation, it seems to work.

2025-01-16 08:28 UTC, soliton- commented on src/scripting/game_lua_kernel.cpp
> + * considering the unit's location(as dst in choose_animation), facing field seems just redundant in this case. I
The target can be in a direction that is exactly between two facing directions. You can say that one will be chosen based on whatever and if it's not the facing that was intended then that's bad luck but it's not redundant.

2025-01-16 14:36 UTC, CelticMinstrel commented
> As the video shows, except for the bug that makes two units hidden after running the animation, it seems to work.

Hmm, I've never actually seen `[move_units_fake]` in action, I think, but that wasn't how I'd imagined it to work. Can anyone who _has_ seen it comment?

The units seeming to disappear after the animation is probably not a bug – the animation is purely aesthetic and doesn't actually move the units. If you assign the unit's coordinates to be the animation endpoint after the animation runs, that should make them not disappear.

2025-01-20 07:20 UTC, Mahoyomu commented on src/scripting/game_lua_kernel.cpp
> + * considering the unit's location(as dst in choose_animation), facing field seems just redundant in this case. I
> The target can be in a direction that is exactly between two facing directions. You can say that one will be chosen based on whatever and if it's not the facing that was intended then that's bad luck but it's not redundant.

I completely understand what you mean, after all you have explained it to me some days before. I just forgot to delete this note, and to delete these redundant notes I need to make this pr work first, so I didn't delete this. Anyway, appreciate for your idea shared ;)

2025-01-26 20:51 UTC, CelticMinstrel commented
I looked at the test scenario, and it does move the units one at a time instead of in a true lockstep. So, as long as this PR is as much as possible reusing the same logic, I think the most recent video seems acceptable.

2025-01-29 19:34 UTC, Mahoyomu commented
> I looked at the test scenario, and it does move the units one at a time instead of in a true lockstep. So, as long as this PR is as much as possible reusing the same logic, I think the most recent video seems acceptable.

Glad to hear it! I've been working on this for a long time, it's really inspiring when I know your most recent idea about my PR is like this. I've fixed the issue that the animated units disappear after animation, and I'll commit soon. Appreciated! ;)

2025-01-29 19:55 UTC, Mahoyomu commented
This is the test video of most recent commit.

https://github.com/user-attachments/assets/713df26a-964f-4482-af0d-84228d534432

As the video shows, the units now show up after the whole animation ended. I'm still considering if it's better to make the unit which already complete all animations assigned to be seen, but for now it works like what in the video.

2025-01-29 21:27 UTC, Mahoyomu commented
> > As the video shows, except for the bug that makes two units hidden after running the animation, it seems to work.
> 
> Hmm, I've never actually seen `[move_units_fake]` in action, I think, but that wasn't how I'd imagined it to work. Can anyone who _has_ seen it comment?
> 
> The units seeming to disappear after the animation is probably not a bug – the animation is purely aesthetic and doesn't actually move the units. If you assign the unit's coordinates to be the animation endpoint after the animation runs, that should make them not disappear.

I've tested it and found that it seems not caused by location not assigned to the endpoint, instead by not set to it's original location immediately before executing 'animator:run()',  after calling `move_units_fake`.

I fixed it this way in the recent commit, as the video shows, it seems to work in my view. Or did I miss something?

2025-02-04 22:12 UTC, soliton- commented on src/units/animation.hpp
> +	int last_movement_serino = 0;
Private member variables should end with an underscore.

2025-02-04 22:21 UTC, soliton- commented
> > > As the video shows, except for the bug that makes two units hidden after running the animation, it seems to work.
> > 
> > 
> > Hmm, I've never actually seen `[move_units_fake]` in action, I think, but that wasn't how I'd imagined it to work. Can anyone who _has_ seen it comment?
> > The units seeming to disappear after the animation is probably not a bug – the animation is purely aesthetic and doesn't actually move the units. If you assign the unit's coordinates to be the animation endpoint after the animation runs, that should make them not disappear.
> 
> I've tested it and found that it seems not caused by location not assigned to the endpoint, instead by not set to it's original location immediately before executing 'animator:run()', after calling `move_units_fake`.
> 
> I fixed it this way in the recent commit, as the video shows, it seems to work in my view. Or did I miss something?

In an effort to move this forward... As far as I can tell celmin said that the animated units disappearing after the animation is done is the expected thing to happen. If the author does not want that they will put the _actual_ units to where they end up in the animation after the animation is done.

So UMC author plays unit animation; after the animation the UMC author changes actual unit positions or not as they see fit.

Thus a commit to wesnoth code cannot possible fix anything about this.

Perhaps what you are talking about is that actual units at some position before the animation are not visible at that position anymore after the animation? That's my guess based on the video anyway. The animation should definitely not change anything about actual units on the map.

2025-02-05 00:12 UTC, Mahoyomu commented
> > > > As the video shows, except for the bug that makes two units hidden after running the animation, it seems to work.
> > > 
> > > 
> > > Hmm, I've never actually seen `[move_units_fake]` in action, I think, but that wasn't how I'd imagined it to work. Can anyone who _has_ seen it comment?
> > > The units seeming to disappear after the animation is probably not a bug – the animation is purely aesthetic and doesn't actually move the units. If you assign the unit's coordinates to be the animation endpoint after the animation runs, that should make them not disappear.
> > 
> > 
> > I've tested it and found that it seems not caused by location not assigned to the endpoint, instead by not set to it's original location immediately before executing 'animator:run()', after calling `move_units_fake`.
> > I fixed it this way in the recent commit, as the video shows, it seems to work in my view. Or did I miss something?
> 
> In an effort to move this forward... As far as I can tell celmin said that the animated units disappearing after the animation is done is the expected thing to happen. If the author does not want that they will put the _actual_ units to where they end up in the animation after the animation is done.
> 
> So UMC author plays unit animation; after the animation the UMC author changes actual unit positions or not as they see fit.
> 
> Thus a commit to wesnoth code cannot possible fix anything about this.
> 
> Perhaps what you are talking about is that actual units at some position before the animation are not visible at that position anymore after the animation? That's my guess based on the video anyway. The animation should definitely not change anything about actual units on the map.

It actually did not change anything about actual units. What I've done in most recent commit is just to achieve this, by making the unit not set to hidden after the animation complete.(After all, It's hidden not because of just set to hidden, but also position not reverted to initial location right after the animation complete, at least for me in my test I came out with this conclusion.) 

Calling "move_units_fake" also don't change the animated units at all, it's position changed during the animation just for the consistency if one unit's last movement animation is expected to be connected with the former, so from what I can tell to make it not change actual units, the thing need to be done here is to restore the initial location of units. And as the video shows, seems that it does work.

2025-02-06 17:01 UTC, soliton- commented
> It actually did not change anything about actual units. What I've done in most recent commit is just to achieve this, by making the unit not set to hidden after the animation complete.(After all, It's hidden not because of just set to hidden, but also position not reverted to initial location right after the animation complete, at least for me in my test I came out with this conclusion.)
>
> Calling "move_units_fake" also don't change the animated units at all, it's position changed during the animation just for the consistency if one unit's last movement animation is expected to be connected with the former. So from what I can tell to make it not change actual units, the thing need to be done here is to restore the initial location of units. And as the video shows, seems that it does work.
 
It's a difficult to understand when you're talking about actual units on the map and when you're talking about fake units used only for animations.

There should be no technical connection between an actual unit and any fake unit used in the animation. (Certainly the fake units can be meant to represent an actual unit but that is just in the mind of the author/player.) There should not be any change in actual units which includes them becoming invisible after the animation. (If the animation played over actual units then that might require a redraw or something.)

I don't know what revert to initial location means and whether that part is about an actual or fake unit.

2025-02-07 12:39 UTC, Mahoyomu commented
> > It actually did not change anything about actual units. What I've done in most recent commit is just to achieve this, by making the unit not set to hidden after the animation complete.(After all, It's hidden not because of just set to hidden, but also position not reverted to initial location right after the animation complete, at least for me in my test I came out with this conclusion.)
> > Calling "move_units_fake" also don't change the animated units at all, it's position changed during the animation just for the consistency if one unit's last movement animation is expected to be connected with the former. So from what I can tell to make it not change actual units, the thing need to be done here is to restore the initial location of units. And as the video shows, seems that it does work.
> 
> It's a difficult to understand when you're talking about actual units on the map and when you're talking about fake units used only for animations.
> 
> There should be no technical connection between an actual unit and any fake unit used in the animation. (Certainly the fake units can be meant to represent an actual unit but that is just in the mind of the author/player.) There should not be any change in actual units which includes them becoming invisible after the animation. (If the animation played over actual units then that might require a redraw or something.)
> 
> I don't know what revert to initial location means and whether that part is about an actual or fake unit.

The part related with animated units I talked about is all about actual unit. In implementation I made, no fake unit is generated. And also I didn't do anything to the process related with fake units, so it's all about actual units. `animated units` is not fake unit, the variable with this name carries data related to actual unit, so I said it that way. If that's confusing then I'm sorry, I didn't want that. TnT

2025-02-09 11:35 UTC, soliton- commented
Ok, so this is not related to [move_units_fake] then, my bad. I have no idea how this should work.

2025-02-10 08:05 UTC, Mahoyomu commented on src/units/animation.hpp
> +	int last_movement_serino = 0;
Should be fine now.(is it?)

2025-02-19 22:08 UTC, Mahoyomu commented
Is this pr considered working? If for now it does seem to work as expected, I'll remove those comments I made for my convenience in the src, and set the status of this pr to ready, for furthur minor alterations.

2025-02-27 21:51 UTC, Mahoyomu commented
I've done cleanups I think, but I noticed there're merge commits in the commit history. It's hard for me to squash them, but if I have to do it myself I'll find a way too.

2025-02-28 01:54 UTC, Pentarctagon commented
Looks like some CI jobs are failing.

2025-03-02 15:55 UTC, CelticMinstrel commented
> Ok, so this is not related to [move_units_fake] then, my bad. I have no idea how this should work.

What do you mean it's not related to `[move_units_fake]`? Is this not a Lua API to exactly that functionality?

I'm a bit confused if this is correct, but the latest video looks fine, I think? As long as _no net changes are made to units_, it should be good to go, I think.

2025-03-02 17:26 UTC, Vultraz requested changes
I've left comments on places that could use cleanup or refinement. It looks like there's significant room to simplify move_units_fake especially without resorting to a ton of intermediate lists. I'd be happy to discuss more on Discord.

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +	game_events::wml_action::map m = game_events::wml_action::registry(); // m[tag] is call wml func by tag.
Woah, this should be a const reference, not a copy! We don't want to duplicate the whole wml action registry. Besides, if it's only used once, you can just dispense with the variable and use `game_events::wml_action::registry()` directly.

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +				uconfig_queues.erase(uconfig_queues.begin() + index);
`uconfig_queues` is local to this function, right? In that case, the additional bookkeeping (erasing) isn't necessary, since the list is going to be destroyed once the function exits anyway. All you need is the config data to invoke the desired tag.

But see my comment above regarding possibly doing away with the extra lists.

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +			bool pair_found = false;
See my comment below. Constructing a separate `initial_uloc_pairs` list might not be necessary. Instead, can you handle `set_standing` here?

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +		for(auto iter = vec.begin(); iter != vec.cend(); iter++) {
Unless you need the iterator, this should be a range-for loop.
```suggestion
		for(auto& anim : vec) {
```

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +	while(temp_index < animated_units_.size() && temp_index < start + size) {
See my comments below regarding intermediate lists. It looks like you should be able to do away with `processed_anim_queues` as well, and simply loop through `animated_units_` at the desired indices.

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +	game_events::wml_action::map m = game_events::wml_action::registry();// m[tag] is call wml func by tag.
Should be a const refence and not a copy, if you need the variable, or if not, just use `game_events::wml_action::registry()` directly.

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +	bool result;
Unnecessary variable. You can replace its use with
```cpp
if(!screen_p->maybe_rebuild()) {
	screen_p->invalidate_all();
}
```

2025-03-02 17:26 UTC, Vultraz commented on src/units/animation.cpp
> +		coherent_moving = last_anim_p && anim.coherence && last_anim_p->is_movement
Just declare this variable here inside the loop instead of outside.

2025-03-02 17:33 UTC, gfgtdf commented
If I understood it correctly this adds a new code path to call the wml implementation of [move_units_fake] to the animator Lua API.

This looks like a rather huge complication of the unit animation code (which now adds a new codepath like "if type is "movement" call [move_units_fake] instead",( which then creates a second animator with a loop to do the actual movement)).

I'm sorry to say this since Mahoyomu surely put effort in this and I really don't like to discourage new promising developers  but:

I don't think it should be merged as-is because imo this features code complications will make it harder to work on this code for simply too little gain, especially since all that it adds for UMC is already possible by just calling [move_unirs_fake] directly. We aren't even sure whether it fixes the use case that was reported in  #9163 by @ProditorMagnus since it doesn't seem to support the main feature of the animator which is simultaneous animations.

2025-03-02 17:41 UTC, Vultraz commented
I second gfgtdf's reservations. Like I mentioned with my review, I do think that could be pared down significantly, and I'm willing to help do that, but I'm still nervous about the overall premise of calling a wml tag directly from C++ (especially through Lua, and using an interface which was meant to handle WML userdata). It feels like an anti-pattern, and without significant reworks, I would not merge this as-is (especially not if it doesn't solve the original issue.)

But I do also want to compliment Mahoyomu for their patience and for wading into the animator code at all, given how much of a black hole it is.

2025-03-02 17:45 UTC, ProditorMagnus commented
Use case was #9161. In #9163 I described smaller reproduction piece.

2025-03-02 19:59 UTC, Mahoyomu commented
> I second gfgtdf's reservations. Like I mentioned with my review, I do think that could be pared down significantly, and I'm willing to help do that, but I'm still nervous about the overall premise of calling a wml tag directly from C++ (especially through Lua, and using an interface which was meant to handle WML userdata). It feels like an anti-pattern, and without significant reworks, I would not merge this as-is (especially not if it doesn't solve the original issue.)
> 
> But I do also want to compliment Mahoyomu for their patience and for wading into the animator code at all, given how much of a black hole it is.

I'll be glad to one day finally implement simultaneous movement in a better way than this, and I understand what gfgtdf is talking about. If there are more things to do, please share some detailed steps or thoughts with me about how I can make it better, like milestones or something. It's encouraging for me to know that what I'm doing does make a difference or is promising to the game. Please share more details about how to implement it in a better way, and I'll try to do that. Appreciate for your reviewing!

2025-03-02 20:06 UTC, Mahoyomu commented
I can also make `real` simultaneous moving in future commits. I just wonder if WML also needs to use it. If it does, then it will just be a replicant of the issue this PR is facing.

2025-03-03 22:44 UTC, gfgtdf commented
> please share some detailed steps or thoughts with me about how I can make it better, like milestones or something

I _think_ i would be better and easer to review if we first handle #9032 and than about #9163 & #9161 in a different pr.

The problem here is a bit that its hard for me to give actual suggesions and milestones since i dont know that part of the code very well (of even how animaions really work in wesnoth) and it's rather hard for me to estimate in advance how hard something would be. For example #9032 looks rather easy at first sight but might actually be quite difficult if its about untangeling unit facings from animation directions i don't really know.

About #9163 i think the final result of adding new functionality should move us towards making #9161 possible which ravana said to be the orignal intention that was desired by (at least one) umc author.

2025-03-05 00:32 UTC, Mahoyomu commented
> > please share some detailed steps or thoughts with me about how I can make it better, like milestones or something
> 
> I _think_ i would be better and easer to review if we first handle #9032 and than about #9163 & #9161 in a different pr.
> 
> The problem here is a bit that its hard for me to give actual suggesions and milestones since i dont know that part of the code very well (of even how animaions really work in wesnoth) and it's rather hard for me to estimate in advance how hard something would be. For example #9032 looks rather easy at first sight but might actually be quite difficult if its about untangeling unit facings from animation directions i don't really know.
> 
> About #9163 i think the final result of adding new functionality should move us towards making #9161 possible which ravana said to be the orignal intention that was desired by (at least one) umc author.

#9032 is already fixed in this PR now; it's just implemented in an unexpected way. IIRC, originally Wesnoth had no working implementation to deal with the direction parameter #9032 mentioned; there's only a `target`, and it will even be automatically overridden when executing `animator:run()`, based on the unit's original facing (meaning that `target` also doesn't work properly).

The work in this PR makes it possible for users to just use directions like `ne`, `nw`, and if the direction given is a coordinate, it can also be properly processed in different ways, depending on whether the needed animation is a movement or not. It also reuses the existing lockstep simultaneous moving implementation (at least I had been told of this before and agreed).

However, like what you have said in the comment section, it actually makes the animation implementation harder to work with, and some corresponding changes are needed here; also, the `real` simultaneous moving needs to be implemented as well. It's pretty much not possible to separate #9032 into an independent PR in my opinion, because the implementation process of the expected direction can't be easily separated from the process of movement and non-movement animations without further worries.

As you can see in the existing code, the current implementation here before this PR is pretty much not working, or at least not as expected, so a fix just for #9032 would possibly be a fix based on unexpected behavior and might cause more trouble in the future (and even regressions) in my view.

2025-07-25 13:39 UTC, CelticMinstrel commented
> I don't think it should be merged as-is because imo this features code complications will make it harder to work on this code for simply too little gain, especially since all that it adds for UMC is already possible by just calling [move_unirs_fake] directly. We aren't even sure whether it fixes the use case that was reported in #9163 by @ProditorMagnus since it doesn't seem to support the main feature of the animator which is simultaneous animations.

It might indeed be the case that, with the state of the PR, there's no clear advantage over just calling `move_units_fake` directly. But having that functionality in the unit animator _in theory_ means that you can animate some units moving around and and others cheering _simultaneously_, which can't be done by calling `move_units_fake`. So I think the principle of putting movement animations as a special case in the animator is sound.

Whether that specific implementation is good is a separate question.

> I second gfgtdf's reservations. Like I mentioned with my review, I do think that could be pared down significantly, and I'm willing to help do that, but I'm still nervous about the overall premise of calling a wml tag directly from C++ (especially through Lua, and using an interface which was meant to handle WML userdata). It feels like an anti-pattern, and without significant reworks, I would not merge this as-is (especially not if it doesn't solve the original issue.)

I agree that calling the WML tag in Lua is not the way to do this. That WML tag is implemented in C++ and uses APIs defined in C++, so the code should just directly use those C++ APIs.

2026-07-12 17:41 UTC, Pentarctagon commented
Closing due to age and the above comments, but feel free to re-open.

2026-07-12 17:41 UTC, closed without merging